masumi-network/sokosumi

.cursor/rules/analysis-process.mdc, .cursor/rules/interface.mdc, .cursor/rules/key-convention.mdc, .cursor/rules/key-principles.mdc, .cursor/rules/lint.mdc, .cursor/rules/naming-convention.mdc, .cursor/rules/optimization.mdc, .cursor/rules/typescript.mdc
This pull request introduces several new guidelines and best practices for various aspects of the project, including analysis process, UI and styling, key conventions, key principles, syntax and formatting, naming conventions, performance optimization, and TypeScript usage. The most important changes are summarized below:
* Added a detailed process for analyzing requests, planning solutions, and implementing strategies in `.cursor/rules/analysis-process.mdc`.
* Established guidelines for using Shadcn UI, Radix, and Tailwind for components and styling, and implementing responsive design with a mobile-first approach in `.cursor/rules/interface.mdc`.
* Defined key conventions for URL search parameter state management, optimizing Web Vitals, and guidelines for using server components and …
=> Add project-specific rules for cursor to improve ai behavior

web-app/src/app/(landing)/components/input-with-button.tsx, web-app/src/app/(landing)/components/trusted-partners.tsx, web-app/src/app/(landing)/page.tsx
This pull request includes several updates to the layout and styling of the landing page components in the `web-app/src/app/(landing)` directory. The main changes involve adjustments to container classes and padding/margin values to improve the overall design and responsiveness. It extracts the positioning code from the component for use on the page.
* The title of trusted partners was not aligned with the content above. It was displayed at the top of the website on large screens.  
* The positioning code, such as padding, was defined in the component instead of where it is used.
* [`web-app/src/app/(landing)/components/input-with-button.tsx`](diffhunk://#diff-62533d6d946799d524aae3c3ddc7a0c348ae9f7a9160e26dedf8d939cad2cf6fL19-R19): Removed redundant padding class from the form element to …
=> Fixes content alignment on the landing page for Trusted Partners

README.md
=> test change (#31)

package-lock.json
After removing `commitlint` we readded it via another pull request.
This pr only did a `npm install`.
=> Remove `commitlint` in package-lock.json

web-app/CLAUDE.md
This pull request includes the addition of a new guidelines document for Claude Code. The document outlines essential commands and code style conventions to be followed by developers.
* [Claude Code Overview](https://docs.anthropic.com/en/docs/agents-and-tools/claude-code/overview)
* [Claude Code Tutorials](https://docs.anthropic.com/en/docs/agents-and-tools/claude-code/tutorials)
* [`web-app/CLAUDE.md`](diffhunk://#diff-28bc4d0bd65c7e7869b3f3844a77e146299b5599245a9b5b6aca760bc9fd3b33R1-R24): Added a new file detailing development commands and code style guidelines for the Sokosumi web application.
Commands:
* Added commands for development, production build, linting, formatting, testing, and Prisma operations.
Code Style:
* Enforced use of TypeScript with strict typing, functional …
=> Add `CLAUDE.md` to improve Claude Code

web-app/src/lib/agent/UnifiedAgent.ts
[x] Bug fix  
[] Other: 
Changed the types, to better work with prisma querying
=> fixed unified-agent

web-app/messages/en.json, web-app/src/app/(app)/components/nav-menu.tsx, web-app/src/app/(app)/components/sidebar/components/agent-add-button.tsx, web-app/src/app/(app)/components/sidebar/components/agents-list.tsx, web-app/src/app/(app)/layout.tsx, web-app/src/app/(landing)/components/navigation.tsx, web-app/types/next-intl.d.ts
* Add `messages` for `app` layout to `en.json`
* Add `next-intl.d.ts` to integrate typescript to `next-intl`
=> I18n app router

README.md
This PR adds detailed documentation about our Git workflow to the README.md file. The new section explains how we follow the GitHub Flow methodology and includes:
- Step-by-step guide for contributing changes
- Information about branch management
- Details about our deployment process
- Clarification on staging and production deployment workflows
- Documentation about our release process using semantic versioning
- Added new "Git Workflow" section to README.md
- Documented GitHub Flow steps
- Added information about staging deployments from main branch
- Included details about production deployment process using GitHub Releases
Having clear documentation about our Git workflow helps new contributors understand how to properly submit changes and helps maintain consistency in our …
=> Add Git workflow documentation to README

web-app/src/app/(auth)/signin/components/form.tsx, web-app/src/app/(auth)/signup/components/form.tsx
Use fieldset inside the form
We can disable all inputs while loading
=> Adding proper form fieldset semantics to improve accessibility

web-app/package-lock.json, web-app/prisma/migrations/20250312091814_initial/migration.sql, web-app/prisma/schema.prisma, web-app/prisma/seed.ts
[x] Bug fix  
[] Other: 
Aggregated rating added to seeding
=> fix(prisma): make agent rating required and update seed data

web-app/src/app/(landing)/components/header.tsx, web-app/src/app/(landing)/components/navigation.tsx, web-app/src/app/(landing)/components/sheet-navigation.tsx
- Fix flex container styling for auth buttons in header
- Adjust navigation menu spacing and center alignment
- Clean up sheet navigation button styling redundancy
- Changed `hidden sm:block` to `hidden sm:flex` for auth buttons container
- Added proper flex container for sheet navigation in mobile view
- Updated navigation menu gap and justification from `justify-around` to `justify-center`
- Moves the responsive visiblity logic to the header component from its children
=> fix(ui): improve header and navigation layout responsiveness

web-app/src/app/(app)/components/header.tsx, web-app/src/app/(app)/components/navigation-menu.tsx, web-app/src/app/(app)/components/sidebar/components/custom-trigger.tsx, web-app/src/app/(app)/layout.tsx, web-app/src/app/(landing)/(auth)/signin/components/form.tsx, web-app/src/app/(landing)/components/auth-buttons.tsx, web-app/src/app/(landing)/components/sheet-navigation.tsx, web-app/src/components/navigation-link.tsx
- Add explicit `undefined` to props.
```typescript
interface Props {
className?: string | undefined
}
```
- Fix responsive issue on sign in page
=> refactor(web-app): props explicit undefined

.github/workflows/dependabot-enable-auto-merge.yml, .github/workflows/test-web-app.yml
This PR introduces two improvements to our GitHub Actions setup:
- ✨ Add Dependabot auto-merge workflow
- Enables auto-merge of Dependabot pull requests (after approve by maintainer)
- Uses fastify/github-action-merge-dependabot@v3
- Configured to use GitHub's auto-merge feature
- 🔄 Update test workflow configuration
- Remove branch restriction to run tests on all pull requests
- Previously only ran on PRs targeting main branch
- This change ensures tests run on all PRs regardless of target branch
These changes will help streamline our dependency management process and improve our testing coverage across all branches.
=> build(ci): enhance GitHub Actions workflows

web-app/eslint.config.mjs, web-app/src/app/(landing)/(auth)/forgot-password/components/form.tsx, web-app/src/lib/better-auth/auth.ts, web-app/tsconfig.json
- Add [`@typescript-eslint/prefer-nullish-coalescing`](https://typescript-eslint.io/rules/prefer-nullish-coalescing) ESLint rule
- Configure TypeScript parser options for ESLint
- Replace logical OR (||) with nullish coalescing (??) operator in:
- Authentication configuration
- Forgot password form
The nullish coalescing operator (??) provides more precise handling of falsy values by only falling back to the default when the value is null or undefined. This prevents unexpected behavior with other falsy values like empty strings or zero.
- Updated ESLint config to enforce nullish coalescing usage
- Fixed social provider configurations to use ?? for environment variables
- Updated form default values to use ?? for better type safety
=> fix(eslint): enforce and implement nullish coalescing operator

web-app/eslint.config.mjs, web-app/messages/en.json, web-app/src/app/(app)/dashboard/page.tsx, web-app/src/app/(landing)/components/footer.tsx, web-app/src/app/(landing)/components/social-button.tsx, web-app/src/app/(landing)/error.tsx, web-app/src/app/(landing)/page/monetize-your-agent.tsx, web-app/src/components/breadcrumb-navigation/breadcrumb-navigation.client.tsx
This PR implements comprehensive internationalization across multiple components by migrating hardcoded strings to translation keys. It also enforces string literal rules through ESLint to prevent future hardcoding.
- Added ESLint rule `react/jsx-no-literals` to prevent hardcoded strings
- Migrated strings to translation keys in:
- Dashboard page
- Footer component
- Social buttons
- Error page
- Breadcrumb navigation
- Monetize Your Agent section
- Added new translation keys for social platforms and navigation
- Updated error message format to support dynamic error IDs
- Added copyright year interpolation
Please verify that:
- All text is properly translated
- Dynamic values (like error IDs and year) are correctly interpolated
- No hardcoded strings remain in the components
=> feat(i18n): migrate hardcoded strings to translation keys

web-app/src/app/(app)/components/sidebar/components/agents-list.tsx
Add link to sidebar pinned agent as `/dashboard/gallery/agent_id`
=> feat(web-app): add link to sidebar pinned agents

web-app/src/app/(app)/dashboard/jobs/[agentId]/components/header.tsx, web-app/src/app/(app)/dashboard/jobs/[agentId]/layout.tsx, web-app/src/components/agents/agent-bookmark-button.tsx
Add bookmark button to job layout header
=> feat(web-app): add bookmark button on job layout header

web-app/messages/en.json
Fix breadcrumb messages
Related to #186 
This PR updates most of routes names which cause  message mismatch.
=> fix(web-app): check breadcrumb messages

web-app/messages/en.json, web-app/src/components/agents/agent-detail.tsx, web-app/src/components/breadcrumb-navigation/breadcrumb-navigation.client.tsx, web-app/src/lib/actions/agent.actions.ts
- Move breadcrumb navigation translations from "Navigation" to "Components.Breadcrumb" namespace
- Replace hardcoded route strings with AppRoute enum constants
- Reorganize translation structure in en.json for better maintainability
=> refactor(navigation): migrate breadcrumb translations and implement route constants

web-app/src/app/app/agents/[agentId]/page.tsx, web-app/src/app/app/agents/page.tsx, web-app/src/app/app/components/sidebar/components/agents-list.tsx, web-app/src/app/app/jobs/[agentId]/components/header.tsx, web-app/src/components/agents/agent-detail.tsx, web-app/src/lib/db/services/agentList.service.ts
This PR refactors the handling of favorite agent lists and enhances the user interface by adding a bookmark button to the agent details page.
**Key Changes:**
*   **Simplified Favorite List Retrieval:** Introduced a dedicated function `getOrCreateFavoriteAgentList` in `agentList.service.ts` to streamline fetching the user's favorite agent list. This replaces previous usages of `getOrCreateAgentListByType` and `getOrCreateAgentListsByTypes` specifically for the `FAVORITE` type, improving code clarity and reducing redundancy.
*   **Updated Components:** Refactored components across the application (`agents/[agentId]/page.tsx`, `agents/page.tsx`, `sidebar/components/agents-list.tsx`, `jobs/[agentId]/components/header.tsx`) to utilize the new `getOrCreateFavoriteAgentList` function.
* …
=> feat: Simplify favorite agent list retrieval and add bookmark button to agent details

web-app/.env.example, web-app/package-lock.json, web-app/package.json, web-app/prisma/seed.ts, web-app/prisma/util/password.ts, web-app/src/config/env.config.ts
This PR enhances the authentication system by implementing secure password hashing and making seed user credentials configurable through environment variables.
- Add `@noble/hashes` package for secure password hashing
- Implement `hashPassword` utility function using scrypt algorithm
- Make seed user email and password configurable via environment variables
- Update seeding process to use hashed passwords
- Add new environment variables:
- `SEED_USER_EMAIL`
- `SEED_USER_PASSWORD`
- Replace hardcoded password hash with dynamically generated secure hash
- Use scrypt algorithm with secure parameters (N=16384, r=16, p=1)
- Implement proper salt generation and storage
To test these changes:
1. Set the new environment variables in `.env` file
2. Run database seeding to verify the new password …
=> feat(auth): implement secure password hashing and configurable seed credentials

web-app/src/lib/job-input/__tests__/job-input.test.ts, web-app/src/lib/job-input/job-input.ts, web-app/src/lib/job-input/type.ts, web-app/src/lib/job-input/validation.ts
[x] Bug fix  
[] Other: 
Fixes optional schema
=> refactor(job-input): change required to optional in validations

.github/workflows/deploy-main.yml, .github/workflows/deploy-release.yml, job-cron-caller/project.yml, registry-cron-caller/project.yml
=> fixing env add

job-cron-caller/src/main.ts, registry-cron-caller/src/main.ts
=> better response messages

.github/workflows/deploy-main.yml, .github/workflows/deploy-release.yml
=> fix: env var for deploy

.github/workflows/deploy-main.yml
=> fix: different env setup testing

.github/workflows/deploy-main.yml
=> feat: global env

.github/workflows/deploy-main.yml, .github/workflows/deploy-release.yml
[] Bug fix  
[x] New feature  
[] Other: 
Automatic deployment of the sync functions to DigitalOcean
=> feat: add sync registry and job to productions

.github/workflows/deploy-main.yml, .github/workflows/deploy-preview.yml, .github/workflows/deploy-release.yml
[] Bug fix  
[x] New feature  
[] Other: 
Sequentially deploy to not overload the deployment
=> feat: multi stage deploy

web-app/.env.example, web-app/.vscode/settings.json, web-app/messages/en.json, web-app/package-lock.json, web-app/package.json, web-app/prisma/seed.ts, web-app/src/app/(landing)/agents/[agentId]/page.tsx, web-app/src/app/(landing)/agents/page.tsx, web-app/src/app/(landing)/components/agents-gallery.tsx, web-app/src/app/api/credit/route.ts, web-app/src/app/app/agents/[agentId]/page.tsx, web-app/src/app/app/agents/components/filtered-agents.tsx, web-app/src/app/app/agents/page.tsx, web-app/src/app/app/jobs/[agentId]/components/create-job-section.tsx, web-app/src/app/app/jobs/[agentId]/components/header.tsx, web-app/src/app/app/jobs/[agentId]/components/right-section.tsx, web-app/src/app/app/jobs/[agentId]/page.tsx, web-app/src/components/agents/agent-card.tsx, web-app/src/components/agents/agent-detail.tsx, web-app/src/components/agents/agents.tsx, web-app/src/config/env.config.ts, web-app/src/lib/db/extension/agent.ts, web-app/src/lib/db/services/agent.service.ts, web-app/src/lib/db/services/credit.service.ts, web-app/src/lib/db/services/job.service.ts
[] Bug fix  
[x] New feature  
[] Other: 
Calculate the price based on the correct conversion and display it with the default decimal conversion.
All calculation are offloaded to the server component to reduce client load and water fall problems
=> feat: pricing calculation

web-app/src/app/api/job/start/route.ts, web-app/src/app/app/jobs/[agentId]/components/create-job-section.tsx, web-app/src/app/app/jobs/[agentId]/components/job-input/job-inputs-form.tsx
[] Bug fix  
[x] New feature  
[] Other: 
Yes it is working :)
=> feat: start job

job-cron-caller/package.json, registry-cron-caller/package.json
=> refactor(web-app): prettify package.json in api callers

web-app/src/app/api/cron/job-sync/route.ts, web-app/src/app/api/cron/registry-sync/route.ts, web-app/src/lib/auth/utils.ts, web-app/src/lib/utils.ts
[x] Bug fix  
[] Other: 
This prevents timing based atacks to itterate the api key
=> fix: securely compare internal api keys to prevent side channel attacks

web-app/prisma/seed.ts
This fixes seed.ts to correctly make job input and output data (as JSON)
Frontend parsing it as json
=> fix(web-app): fix job input output seeding

web-app/package.json, web-app/pnpm-lock.yaml, web-app/src/app/api/cron/registry-sync/route.ts, web-app/src/app/app/agents/components/filter-section.tsx, web-app/src/app/app/agents/components/filtered-agents.tsx, web-app/src/app/app/agents/components/use-gallery-filter.ts, web-app/src/app/layout.tsx, web-app/src/config/env.config.ts
This PR introduces agent tags to the registry sync and refactors the filter state management using the `nuqs` library.
-   **Agent Tag Filtering:** Users can now filter agents in the gallery based on associated tags. The selected tags are reflected in the URL query parameters.
-   **Registry Sync Update:** The cron job responsible for syncing agent data from the registry (`/api/cron/registry-sync`) now includes processing and storing agent tags.
-   **Query State Management:** Replaced the custom implementation in `use-gallery-filter.ts` with the `nuqs` library for managing URL query state (`query` and `tags`). This simplifies the hook and removes the need for manual debouncing and URL parsing/updating.
-   **Root Layout:** Integrated `NuqsAdapter` into the root layout …
=> fix(agent): Add agent tags and refactor query state management

job-cron-caller/package.json, package.json, registry-cron-caller/package.json, web-app/package.json
Update the packageManager version to pnpm@10.8.1 in all package.json files to ensure consistency and take advantage of the latest features and fixes.
=> chore: update packageManager version to pnpm@10.8.1

web-app/pnpm-lock.yaml, web-app/src/components/ui/badge.tsx, web-app/src/components/ui/breadcrumb.tsx, web-app/src/components/ui/button.tsx, web-app/src/components/ui/card.tsx, web-app/src/components/ui/drawer.tsx, web-app/src/components/ui/dropdown-menu.tsx, web-app/src/components/ui/form.tsx, web-app/src/components/ui/input.tsx, web-app/src/components/ui/scroll-area.tsx, web-app/src/components/ui/sheet.tsx, web-app/src/components/ui/sidebar.tsx, web-app/src/components/ui/skeleton.tsx, web-app/src/components/ui/sonner.tsx, web-app/src/components/ui/tooltip.tsx
- Updated all Shadcn UI components to their latest versions for improved features, bug fixes, and compatibility.
- Ensured all components are aligned with current Shadcn best practices and design tokens.
- Verified compatibility with Tailwind CSS and Radix UI.
- Confirmed support for both dark and light modes.
- No hardcoded colors; all styling leverages Tailwind and Shadcn tokens.
- Manually reviewed all updated components in both light and dark themes.
- Checked for visual regressions and interaction bugs.
- Validated responsive behavior across breakpoints.
- Keeps our UI modern, maintainable, and secure.
- Leverages the latest accessibility and performance improvements from Shadcn.
- Prepares the codebase for future enhancements and easier maintenance.
* Relates to #374: Extract the …
=> chore(ui): update all Shadcn UI components to latest version ✨🛠️

web-app/src/app/(landing)/components/header.tsx
- Updated the header’s background opacity from `bg-background/20` to `bg-background/5` in the `Header` component.
- This change subtly increases the transparency of the header, enhancing the visual layering effect and improving the overall aesthetic.
- The header now appears lighter and less visually intrusive, especially when content scrolls beneath it.
- Maintains compatibility with both light and dark modes.
- Fully responsive and continues to use Tailwind CSS and Shadcn UI conventions.
=> fix(ui): adjust header background opacity for improved visual clarity ✨

web-app/messages/en.json, web-app/src/app/(landing)/components/number-talks.tsx
This PR refactors the "Number Talks" section on the landing page to improve maintainability, modularity, and internationalization:
- ♻️ Refactored the `NumberTalks` component to use a reusable `NumberTalkSection` subcomponent for each metric.
- 🌐 Integrated `next-intl` for all static text, enabling full internationalization of titles, descriptions, and captions.
- 🎨 Ensured UI consistency and accessibility by leveraging Shadcn UI, Radix, and Tailwind CSS best practices.
- 🧹 Removed hardcoded strings and icons, replacing them with dynamic, translation-driven content.
- 📁 Updated the English translation file (`en.json`) to match the new structure and content requirements.
- Easier to add or update metrics in the future.
- All text is now translatable, supporting a global audience.
- Code is …
=> refactor(landing): Number Talks section for i18n and modularity 🌐✨

job-cron-caller/package.json, package.json, registry-cron-caller/package.json, web-app/package.json
* Update [`pnpm`](https://pnpm.io) from [10.8.1](https://github.com/pnpm/pnpm/releases/tag/v10.8.1)  to [10.9.0](https://github.com/pnpm/pnpm/releases/tag/v10.9.0)
=> chore(deps): Update pnpm from 10.8.1 to 10.9.0

web-app/messages/en.json, web-app/src/app/(landing)/agents/components/featured-agent.tsx, web-app/src/app/(landing)/agents/page.tsx
This PR introduces a comprehensive redesign of the featured agent component to improve user experience and add pricing information.
Changes:
- 🎨 Update layout to use 50/50 split instead of 33/66
- ✨ Add pricing display with credit amounts
- 💄 Add verification badge with green checkmark
- 🔤 Update translation strings for new UI elements
- ✨ Add separate "View" and "Hire" action buttons
- 💄 Improve typography with new font weights and sizes
- ♿️ Enhance responsive design for mobile and desktop views
The new design provides clearer pricing information and calls-to-action while maintaining a clean, modern aesthetic that works well in both light and dark modes.
=> feat(agents): redesign featured agent component with pricing

web-app/src/app/app/agents/[agentId]/jobs/components/jobs-table.tsx, web-app/src/app/globals.css, web-app/src/components/agents/agent-card.tsx, web-app/src/components/data-table/data-table.tsx
* Remove horizontal scroll bar on table
* Remove table-fixed class name because we use fixed width on its parent
* Change global css for card bg color, and simplify agent card class name
=> chore: remove horizontal scroll on table

job-cron-caller/package.json, package.json, registry-cron-caller/package.json, web-app/package.json
* update pnpm from `10.9.0` to [`10.10.0`](https://github.com/pnpm/pnpm/releases/tag/v10.10.0)
=> chore(deps): update pnpm from 10.9.0 to 10.10.0

web-app/src/components/agents/agent-modal/agent-modal.tsx
* Remove outline of Agent Modal (which is not looking good)
=> chore: remove outline in agent modal

web-app/.do/app.yaml
=> chore(deploy): update GOOGLE_CLIENT_ID value in app configuration

web-app/src/components/agents/agent-card.tsx
* Add missing `return` statement
=> chore: fix agent card wrapper

web-app/src/components/agents/agent-modal/card-sections/card-section-1.tsx
This PR updates the background blur effect in the `CardSection1` component of the agent modal to ensure visual consistency with the card's rounded corners.
- Removes the `bg-foreground` class from the blurred background div.
- Adds `rounded-lg` to the blurred background div to match the card's border radius.
- Ensures the blurred background effect aligns with the card's shape, improving UI polish and consistency.
Previously, the blurred background behind the agent image did not respect the card's rounded corners, resulting in a visual mismatch. This change ensures the blur effect is contained within the same rounded shape as the card, providing a more cohesive and professional appearance.
- Verified that the blurred background now matches the card's rounded corners in both light and dark …
=> fix(ui): update agent card image background

sync-function/src/main.ts
This PR addresses a race condition in the lock logic that was occurring when synchronizing agents and jobs. Previously, the `callApi` functions for agents and jobs were executed in parallel using `Promise.all`. This could lead to a situation where both API calls attempted to acquire or release locks simultaneously, resulting in inconsistent or unexpected behavior.
- Refactored the API calls for agents and jobs to execute sequentially rather than in parallel.
- This change ensures that the lock logic is respected and prevents potential race conditions during the sync process.
The parallel execution of these API calls was causing intermittent failures due to race conditions in the lock management. By serializing the calls, we ensure that the lock is properly acquired and released for each …
=> fix(sync): work around race condition in lock logic by serializing agents and jobs API calls

web-app/src/app/layout.tsx
This PR enhances the Plausible analytics integration in the application layout by enabling two additional tracking features:
- **File Download Tracking:**  
Adds `trackFileDownloads={true}` to the `PlausibleProvider`, allowing automatic tracking of file download events.
- **Hash Tracking:**  
Adds `hash={true}` to the `PlausibleProvider`, enabling tracking of URL hash changes as pageviews.
These improvements provide more comprehensive analytics for user interactions, particularly for file downloads and single-page application navigation via hash changes. No breaking changes are introduced.
=> feat(analytics): enable file download and hash tracking in Plausible analytics

sokosumi.code-workspace
This pull request introduces a dedicated code workspace for the sokosumi project. The workspace is designed to streamline development, improve project organization, and enhance the overall developer experience.
- Added a new code workspace configuration tailored for sokosumi.
- Structured the workspace to support modular development and easier navigation.
- Ensured compatibility with existing project tooling and conventions.
The addition of a code workspace enables:
- Centralized management of project settings and dependencies.
- Improved collaboration among team members.
- Simplified onboarding for new contributors.
- No breaking changes introduced.
- All existing functionality remains unaffected.
* https://code.visualstudio.com/docs/editing/workspaces/workspaces
* …
=> feat(workspace): add code workspace for sokosumi

web-app/messages/en.json, web-app/src/app/app/agents/[agentId]/jobs/@right/components/create-job-section.tsx, web-app/src/app/app/agents/[agentId]/jobs/@right/components/job-input/job-inputs-form.client.tsx, web-app/src/app/app/agents/[agentId]/jobs/@right/components/job-input/job-inputs-form.tsx
* Add Accept terms and privacy and other legal link above job input `submit` button
We only use agents' legal links, if they don't have one, we don't show them.
=> chore: add accept terms string above submit button

web-app/src/app/(auth)/components/auth-background.tsx
This pull request updates the authentication hero background image to enhance the visual appeal and align with the latest design direction.
- Replaces the previous background image (`moody-1.png`) with the new `ink-gradient-3.png` in the `AuthBackground` component.
- Ensures the new image is used across all authentication-related pages.
- No changes to layout, accessibility, or logic—purely a visual update.
This change maintains full compatibility with dark and light modes and leverages existing responsive and accessibility best practices. No breaking changes or additional dependencies introduced.
=> feat(auth): update auth hero background image

web-app/src/app/app/agents/[agentId]/jobs/components/jobs-table.tsx, web-app/src/app/app/components/sidebar/components/agent-list.tsx, web-app/src/app/app/layout.tsx
* Fix colors on sidebar agent list
* Fix colors on Job table's row
* Fix "only text is clickable on sidebar agent list" issue
=> refactor: fix colors in sidebar and job table

web-app/public/js/plain.js
This PR updates the Plain live chat integration script in `public/js/plain.js` to enhance user engagement and align with our brand. The following changes were made:
- Added a `links` section to the Plain widget, featuring a "Feedback and Feature Requests" link that directs users to our Featurebase portal.
- Set custom brand colors and launcher icon color to match our design system.
- Ensured the widget uses the "auto" theme and is positioned with consistent spacing from the right and bottom edges.
- Confirmed that authentication is required for chat access.
These improvements make it easier for users to provide feedback and request features directly from the chat widget, while also ensuring the widget is visually consistent with our application.
=> feat(plain): add feedback and feature requests link to plain.js

web-app/src/app/app/agents/[agentId]/jobs/components/header.tsx, web-app/src/app/app/agents/[agentId]/page.tsx
* Show book mark button on agent detail page on app context
* show book mark on agent detail from CTA on job page
=> fix: show bookmark button on agent detail page on app context

web-app/src/app/app/agents/[agentId]/jobs/components/header.tsx, web-app/src/app/globals.css, web-app/src/components/agents/agent-detail/agent-detail.tsx, web-app/src/components/agents/agent-detail/card-section.tsx
* Add `className` to CardSection Props to use customized className for Agent Detail and Agent Modal.
* Changes Agent Modal Card background colors
* Accidentally use same color on Agent Modal Card as Agent Detail Card.
Will close #MAS-107
=> chore: fix agent modal card colors

web-app/src/app/(auth)/components/form/organization-input/create-organization.tsx, web-app/src/app/(auth)/components/form/organization-input/organization-input.tsx, web-app/src/app/(auth)/register/page.tsx, web-app/src/lib/actions/organization/action.ts, web-app/src/lib/db/organization/repo.ts
* fix revalidate path after creating organization
* fix padding issue on register's organization form
* change function name `getAllOrganizations` to `getOrganizations`
* change `form` tag to `div` tag on create organization input (because it cause form tag inside form tag)
=> fix: revalidate path after creating org

web-app/pnpm-lock.yaml
* Fix pnpm lock file (which was broken)
=> fix: update pnpm lock file

.github/workflows/deploy-main-sync-function.yml, .github/workflows/deploy-main-webapp.yml, README.md, sync-function/README.md, sync-function/package.json, web-app/README.md
This PR updates and clarifies all README files across the monorepo:
- **Monorepo root README**: Improved project structure, setup, development, deployment, and contribution instructions. Clearer separation of web-app and sync-function packages.
- **web-app/README.md**: Updated to reflect monorepo usage, pnpm, and modern Next.js 15/React 19 stack. Improved setup, scripts, and database seeding instructions.
- **sync-function/README.md**: Rewritten for clarity, with explicit local development, environment, and DigitalOcean deployment steps. Added script explanations.
- Ensure onboarding is smooth for new contributors.
- Reflect current tech stack and monorepo structure.
- Remove outdated or inaccurate instructions.
- No application code or configuration was changed—only documentation.
- …
=> docs(readme): update and clarify all README files for monorepo, web-app, and sync-function

web-app/prisma/migrations/20250611153252_add_oncacade_referential_action_on_agent_list/migration.sql, web-app/prisma/schema.prisma
* Add `Cascade` referential action on AgentList model for user relations
* When user is deleted, its AgentList row will also be deleted.
=> fix(prisma): add Cascade referential action to AgentList

web-app/src/app/app/agents/[agentId]/jobs/@right/components/job-details/job-details.tsx
* When  job status is Completed and output is given, we will only show output accordion
=> refactor: when output is give close all other accordion

web-app/src/lib/services/job/service.ts, web-app/src/lib/utils/index.ts
This PR updates hashes in accordance with MIP-004
=> feat: update hashes according to MIP-004

web-app/public/legal/privacy-policy.md
Update the wording of the privacy policy
=> feat: add new privacy policy

web-app/src/components/agents/agent-detail/section-5.tsx, web-app/src/components/create-job-modal/job-input/job-inputs-form.client.tsx
The targets for external privacy links are now "_blank" instead of internal
=> fix: link targets

web-app/src/lib/actions/job/action.ts
Add logs on more catch clauses with error messages
=> feat: add error logs

web-app/prisma/migrations/20250519112751_job_sync/data-migration.ts, web-app/prisma/migrations/20250520120625_add_organization/data-migration.ts, web-app/src/app/api/stripe/webhook/route.ts, web-app/src/lib/services/job/service.ts, web-app/src/lib/services/stripe/service.ts
Add more logs to failed prisma db transactions
=> feat: add logs to failed prisma transactions

web-app/src/app/api/stream/job-status/route.ts, web-app/src/components/cookie-consent.tsx, web-app/src/hooks/use-job-status-event.tsx, web-app/src/lib/db/listener/schema.ts
* Send date string in interval on job status event stream to keep connection alive.
* Make cookie consent animated when appear and disappear
=> refactor: keep alive job status event stream

web-app/messages/en.json, web-app/src/app/(auth)/components/form/organization-input/create-organization.tsx, web-app/src/app/(auth)/components/form/organization-input/organization-input.tsx
This PR improves the organization selection and creation experience in the sign-up form by implementing a more intuitive two-step flow that separates organization selection from organization creation.
- **Separated Creation Flow**: Organization creation is now a dedicated step with its own interface, providing better focus and clarity
- **Back Navigation**: Added a back button in the creation form to return to the organization selection view
- **Improved State Management**: Better handling of creation vs selection states with dedicated `creating` state
- **Enhanced Visual Hierarchy**: Clear separation between "New Organization" button and existing organization list
1. **Initial View**: User sees search input, "New Organization" button, and existing organizations list
2. **Create New**: …
=> refactor: improve create organization UX

web-app/CLAUDE.md
This PR updates the `CLAUDE.md` file to provide more comprehensive guidance for contributors and AI assistants working with the Sokosumi web app. Key changes include:
- Expanded the list of available pnpm commands, including Prisma and testing scripts.
- Clarified code style conventions, directory structure, and import alias usage.
- Added a detailed "Architecture Overview" section covering:
- Core technologies (Next.js 15, TypeScript, Prisma, Tailwind CSS, shadcn/ui, etc.)
- Key architecture patterns: service layer, action layer, repository pattern, and API integration.
- Authentication and authorization flows.
- Database schema highlights.
- Integration with external services (Masumi Registry, Payment, Stripe, Resend).
- Development patterns and best practices (server/client components, …
=> docs: update CLAUDE.md with expanded guidelines and architecture overview

web-app/src/components/data-table/data-table-column-header.tsx, web-app/src/components/data-table/data-table.tsx, web-app/src/components/members-table/invitation-actions-dropdown.tsx, web-app/src/components/members-table/member-actions-dropdown.tsx
This PR addresses alignment inconsistencies in the data tables (jobs table and members table) by standardizing padding across all table cells and headers.
- **File**: `web-app/src/components/data-table/data-table-column-header.tsx`
- **Change**: Added consistent `p-2` padding to non-sortable column headers
- **Impact**: Ensures all column headers have uniform spacing regardless of sort functionality
- **File**: `web-app/src/components/data-table/data-table.tsx`
- **Changes**:
- Added `p-2` padding to all `TableHead` elements
- Added `p-2` padding to all `TableCell` elements
- **Consistent Spacing**: All table cells now have uniform 8px padding (`p-2`)
- **Better Alignment**: Headers and cells are properly aligned across all columns
- ✅ Verified alignment consistency across all table …
=> refactor: enhance alignment data table

web-app/src/components/agents/agent-card.tsx, web-app/src/components/agents/agent-detail/section-1.tsx, web-app/src/components/create-job-modal/create-job-section.tsx
* Fix image container style on create-job-modal and agent card.
=> fix(agents): adjust image container styles

web-app/src/app/globals.css
This PR updates the dark mode background gradient for the landing page hero section to improve visual consistency and accessibility. The new gradient uses a more vibrant purple overlay, enhancing contrast and aligning with the updated design direction.
**Changes:**
- Modified the `@utility landing-hero-bg` dark variant in `globals.css`:
- Updated the linear-gradient overlay to use `rgba(79, 0, 197, 0.62), rgba(0, 0, 0, 1)` for a richer, more accessible effect.
- Ensured no hardcoded hex values are used; all colors leverage RGBA or CSS variables.
- Verified compatibility with both light and dark modes.
**Why:**
- Improves visual appeal and accessibility in dark mode.
- Aligns with design system and color usage guidelines.
- Ensures a consistent user experience across themes.
**Testing:**
- …
=> feat(ui): update dark mode hero background gradient for landing page

web-app/src/app/(landing)/components/agent-search-input.tsx
Update Agent Search Input's Input tag's background to `bg-transparent`.
=> fix: agent search input's background

pnpm-lock.yaml, web-app/package.json
This pull request creates a test branch to verify the functionality of Vercel preview deployments.  
No code changes are included—this branch is solely for testing the deployment pipeline and ensuring that preview environments are generated correctly for pull requests.  
No production impact is expected.
=> chore: test Vercel preview deployments

.github/workflows/claude.yml
Enhanced the Claude GitHub Actions workflow to better support the project's pnpm-based development environment and provide proper tool permissions for CI operations.
- **Added pnpm installation step**: Uses `pnpm/action-setup@v4` to ensure pnpm is available in the CI environment
- **Configured tool permissions**: Added `allowed_tools` configuration to enable:
- `Bash(pnpm install)` - Package installation
- `Bash(pnpm run lint)` - Code linting
- `Bash(pnpm run test)` - Running tests
- `Bash(git:*)` - Git operations
- **Added CI environment variable**: Set `CI: true` to ensure tools run in CI mode
=> feat(ci): enhance Claude workflow with pnpm installation and environment configuration

pnpm-lock.yaml, web-app/package.json, web-app/src/components/markdown.tsx, web-app/src/lib/utils/sanitizeMarkdown.ts
- ✅ **Added a custom handler** to parse `<video>` tags inside Markdown files, enabling direct embedding of video content.
- ✅ **Disabled raw HTML parsing** (`disableParsingRawHTML`), which typically prevents any HTML tags from being rendered. This is a security measure to avoid XSS and other vulnerabilities.
- ✅ **Introduced a sanitization helper** to allow only safe `<video>` attributes and sources, mitigating risks when video tag support is enabled.
- ✅ **Fallback logic**: If the `<video>` tag is not supported or considered unsafe, the output gracefully falls back to Markdown image syntax (`![video]`), which displays a link or thumbnail instead of an embedded player.
- ✅ **Test coverage includes**:
- Valid `<video>` tags with sources and fallback links
- Unsafe `<script>` tags to verify …
=> fix: adding Sanitize Markdown and Video tag handler

web-app/src/components/agents/agent-action-buttons.tsx
Minor fix removing the window object use, the behavior when we're on mobile, we're going to back to the `Agents` page as it's our `Home` page.
=> fix(back-button): Fix back button window error on server

web-app/src/components/agents/agent-card.tsx
Fix Agent author image's side to fit correctly
=> fix(agent-card): adjust author image container size

web-app/src/app/(app)/components/header.tsx, web-app/src/components/create-job-modal/job-input/job-inputs-form.client.tsx
- **Remove unnecessary information**: Set credit to `Free` and remove job's execution time for Demo Jobs.
- **Extracted demo state**: Introduced `isDemo` variable to replace repeated `!!demoValues` checks
- **Consistent demo handling**: Applied the `isDemo` variable across all demo-dependent UI elements
- Fix app layout's header z-index from 100 to 50
=> refactor(job-input): remove price and execution time for demo jobs

web-app/next.config.ts, web-app/prisma/migrations/20250828155121_add_columns_filename_size/migration.sql, web-app/prisma/schema.prisma, web-app/src/app/(app)/agents/[agentId]/jobs/@right/components/job-details/inputs.tsx, web-app/src/app/(app)/agents/[agentId]/jobs/@right/components/job-details/job-details.tsx, web-app/src/components/ui/file-chip.tsx, web-app/src/components/ui/file-upload.tsx, web-app/src/lib/actions/job/action.ts, web-app/src/lib/actions/job/utils.ts, web-app/src/lib/db/repositories/blob.repository.ts, web-app/src/lib/db/types/job.ts, web-app/src/lib/utils/file.ts, web-app/src/lib/utils/format-bytes.ts
Introduces first-class support for file-type job outputs end-to-end for the input section: database schema, repository, server actions, and UI. Includes a migration to store filename and size, reusable file utilities, and a compact file chip component.
- **Database**
- Add `filename` and `size` columns via migration: `web-app/prisma/migrations/20250828155121_add_columns_filename_size/migration.sql`
- Update Prisma schema: `web-app/prisma/schema.prisma`
- **Domain/Server**
- Extend types for file outputs: `web-app/src/lib/db/types/job.ts`
- Update repository for file metadata: `web-app/src/lib/db/repositories/blob.repository.ts`
- Adjust job actions and helpers for file outputs: `web-app/src/lib/actions/job/action.ts`, `web-app/src/lib/actions/job/utils.ts`
- **UI**
- Add `FileChip` for …
=> feat(job-output): add file input support and UI

web-app/.env.example, web-app/src/app/layout.tsx, web-app/src/components/usersnap/usersnap-provider.tsx, web-app/src/config/env.secrets.ts
This PR enhances the application's environment configuration management and refactors third-party service integrations to be more flexible and maintainable.
- **Added `DRAFT_USER_CENTRICS` flag**: Replaces hardcoded network-based logic with a configurable environment variable for Usercentrics draft mode
- **Added `USERSNAP_SPACE_API_KEY`**: Makes Usersnap integration configurable through environment variables instead of hardcoded values
- **Usersnap Provider**: 
- Removed hardcoded API key
- Added `usersnapSpaceApiKey` prop for dynamic configuration
- **Usercentrics Integration**:
- Replaced network-based draft mode logic (`isMainnet`) with environment-driven configuration
- More flexible deployment across different environments
- **Updated `.env.example`**: Added new environment …
=> refactor(env): add draft Usercentrics flag and Usersnap space api key

web-app/src/app/(app)/agents/[agentId]/jobs/layout.tsx, web-app/src/app/(app)/layout.tsx, web-app/src/components/markdown.tsx
This PR enhances the application's layout responsiveness and adds proper table rendering support in markdown content.
**Layout Improvements:**
- **Job Layout**: Added `w-full` class to the main container in `jobs/layout.tsx` to ensure full width utilization
- **App Layout**: Enhanced sidebar and main content area responsiveness:
- Added `max-w-svw` and `overflow-clip` classes to `SidebarProvider` for better viewport handling
- Updated main content container with `min-w-0 flex-1` classes for proper flex behavior
- Improved overflow handling across the layout hierarchy
**Markdown Enhancement:**
- **Table Support**: Added responsive table rendering in `markdown.tsx`:
- Wrapped tables in `overflow-x-auto` container for horizontal scrolling on small screens
- Applied `w-full min-w-full` …
=> fix(layout): improve layout responsiveness and table in markdown

pnpm-lock.yaml, web-app/package.json, web-app/src/lib/db/helpers/credit.ts, web-app/src/lib/services/agent.service.ts
This PR enhances the credit calculation system by adding high-precision decimal arithmetic support and implementing proper rounding logic for agent pricing. The changes ensure accurate financial calculations while maintaining integer credit display for better user experience.
- **Added `decimal.js` dependency** for high-precision decimal arithmetic
- **Updated `convertCentsToCredits()`** to handle large numbers safely using Decimal.js when values exceed `Number.MAX_SAFE_INTEGER`
- **Updated `convertCreditsToCents()`** to use Decimal.js for precise multiplication and floor operations
- **Added `roundUpTotalCents()` helper function** that rounds up total cents to show credits as integers
- **Integrated rounding logic** into agent pricing calculation to ensure consistent integer credit …
=> fix:  ceil agents price to be full integer

WARP.md
This PR adds a comprehensive WARP.md guidance file to help future Warp instances work effectively in the Sokosumi repository.
- **Added WARP.md**: Comprehensive guidance file for Warp terminal AI assistance
- **Command Reference**: Complete command documentation for monorepo operations, web app development, database management, and testing
- **Architecture Documentation**: Detailed explanation of the three-layer service architecture (Repository → Service → Action)
- **Development Patterns**: Code style guidelines, import aliases, and conventions specific to this codebase
- **Setup Instructions**: Step-by-step development environment setup
- **Production Information**: URLs and deployment details
The WARP.md file includes:
1. **Commands Section**: Organized by category (monorepo, web app, …
=> docs: add WARP.md guidance file for repository

.cursor/commands/create-pr.md, .cursor/commands/plan-issue.md, .cursor/commands/update-pr.md, pnpm-lock.yaml, web-app/package.json
This PR updates multiple dependencies to their latest versions and improves the Cursor IDE command templates for better development workflow.
- **@prisma/client**: 6.16.2 → 6.16.3
- **@sentry/nextjs**: 10.16.0 → 10.17.0  
- **@sparticuz/chromium**: 138.0.2 → 140.0.0
- **puppeteer-core**: 24.15.0 → 24.22.3
- **puppeteer**: 24.15.0 → 24.22.3
- **@hey-api/openapi-ts**: 0.84.3 → 0.84.4
- **@types/node**: 22.18.6 → 22.18.7
- **@types/react**: 19.1.15 → 19.1.16
- **Renamed**: `create-pull-request-on-github.md` → `create-pr.md` for better naming
- **Fixed**: Removed unnecessary % symbol in chore category description
- **Added**: New `plan-issue.md` command for Linear issue implementation planning
- **Added**: New `update-pr.md` command for updating existing pull requests
All dependency updates …
=> chore(deps): update dependencies and improve cursor commands

.cursor/commands/create-pr.md, web-app/.cursor/rules/interface.mdc
This PR updates the Cursor interface rules to enhance UI and styling guidelines for the project.
- **Enhanced styling guidelines**: Added specific rules for semantic colors and consistent sizing
- **Improved formatting**: Fixed whitespace and formatting issues in the interface rules file
- **Better developer experience**: Added clear guidance on using `size-4` instead of `h-4` and `w-4`
- Added rule to use semantic colors defined in `globals.css`
- Added rule to use `size-4` instead of `h-4` and `w-4` for consistent sizing
- Fixed formatting issues (trailing whitespace, missing newline)
- Improved readability with proper spacing
- **Consistency**: Ensures all developers follow the same styling patterns
- **Maintainability**: Semantic colors make theme changes easier to manage
- …
=> chore(cursor): update interface rules for UI and styling guidelines
