masumi-network/sokosumi

- web-app/.vscode/settings.json
- web-app/messages/en.json
- web-app/next.config.ts
- web-app/package-lock.json
- web-app/package.json
- web-app/src/app/(landing)/page.tsx
- web-app/src/app/layout.tsx
- web-app/src/i18n/request.ts
- web-app/src/lib/auth.client.ts
This is only the basic setup. I will use it on the landing page as soon as #37 merged.
This pull request includes several changes to add internationalization support to the web application and improve the development environment. The most important changes include the integration of the `next-intl` package.
Related to #39
> Use `next-intl` as internationalization framework

- web-app/package-lock.json
- web-app/package.json
Updated packages in the web-app:
- [next-intl](https://www.npmjs.com/package/next-intl) to version 4.0.2
- Introduces ESM-only build output
- Adds strictly-typed locale support
- Improves type safety across the app
- Modernizes build output with enhanced tree-shaking
- [tailwindcss](https://www.npmjs.com/package/tailwindcss) to version 4.0.14
- Latest version of the utility-first CSS framework
- Includes performance improvements and bug fixes
- [@tailwindcss/postcss](https://www.npmjs.com/package/@tailwindcss/postcss) to version 4.0.14
- Updated to match tailwindcss core version
Additional package updates:
- [@babel/core](https://www.npmjs.com/package/@babel/core) to version 7.26.10
- [@babel/generator](https://www.npmjs.com/package/@babel/generator) to version 7.26.10
- …
> build(deps): update dependencies in /web-app

- web-app/messages/en.json
- web-app/src/app/(landing)/(auth)/actions.ts
- web-app/src/app/(landing)/(auth)/components/social-buttons.tsx
- web-app/src/app/(landing)/(auth)/forgot-password/components/form.tsx
- web-app/src/app/(landing)/(auth)/signin/components/form.tsx
- web-app/src/app/(landing)/(auth)/signin/page.tsx
- web-app/src/app/(landing)/(auth)/signup/components/form.tsx
- web-app/src/app/(landing)/(auth)/signup/page.tsx
- web-app/src/lib/auth.ts
This PR adds social authentication functionality to the application, allowing users to sign in with Google, Microsoft, Apple, and LinkedIn accounts.
- Add server action for handling social authentication
- Configure social provider credentials in auth configuration
- Update SocialButtons component to handle authentication flow
- Improve error handling and success messages for authentication
- Standardize error message handling across auth forms
- Update translations for social authentication messages
- `GOOGLE_CLIENT_ID` and `GOOGLE_CLIENT_SECRET`
- `MICROSOFT_CLIENT_ID` and `MICROSOFT_CLIENT_SECRET`
- `APPLE_CLIENT_ID` and `APPLE_CLIENT_SECRET`
- `LINKEDIN_CLIENT_ID` and `LINKEDIN_CLIENT_SECRET`
No need for a `NEXT_PUBLIC` prefix; it's all server-side.
* Re-add the SocialButton component …
> feat(auth): implement social authentication providers

- web-app/src/middleware.ts
- web-app/src/middleware/authorization.ts
Adds middleware functionality to protect `dashboard/:path*` routes with session-based authentication.
- Creates main middleware configuration that runs on `/dashboard/*` routes
- Implements authorization middleware to check for valid session cookies
- Redirects unauthenticated users to the signin page
- Uses better-auth package for cookie management
- Middleware is configured to run only on dashboard routes for performance
- Authorization check is performed before any other middleware
- Follows Next.js 13+ middleware patterns
- Type-safe implementation using NextRequest/NextResponse
Please verify:
- Accessing dashboard routes without authentication redirects to signin
- Valid session cookies allow access to dashboard routes
- Non-dashboard routes remain accessible without authentication
> feat(auth): implement authentication middleware for dashboard routes

- web-app/messages/en.json
- web-app/src/app/(landing)/(auth)/data.ts
- web-app/src/app/(landing)/(auth)/reset-password/data.ts
- web-app/src/app/(landing)/(auth)/signin/actions.ts
- web-app/src/app/(landing)/(auth)/signup/actions.ts
- web-app/src/app/(landing)/(auth)/signup/components/form.tsx
- web-app/src/app/(landing)/(auth)/signup/data.ts
- web-app/src/constants/index.ts
- web-app/src/lib/better-auth/auth.ts
- web-app/src/lib/email/reset-password.tsx
- web-app/src/lib/email/verification.tsx
This PR improves the authentication system by standardizing field names and password constraints across the application.
Key Changes:
- Renamed "Username" field to "Name" throughout the application for better clarity
- Added PASSWORD_MAX_LENGTH constant (128 characters)
- Implemented consistent password length validation across all auth forms
- Configured better-auth to use the same password length constraints
- Removed debug console.log from signin action
- Added SOKOSUMI_URL constant to constants file
- Updated email templates to use "name" instead of "username"
- Password constraints are now centralized in constants (min: 8, max: 128)
- Removed regex validation for name field (previously restricted to letters, numbers, and underscores)
- Updated translations to reflect the field name …
> refactor(auth): rename username to name and standardize password constraints

- .do/app.yaml
This PR adds environment variables for OAuth provider credentials to the DigitalOcean app configuration. This enables passing information from GitHub to DigitalOcean for:
- Google
- Microsoft
- LinkedIn
- Apple
Each provider requires both a client ID and client secret to be configured. These values will be injected via environment variables at runtime.
_Note: Make sure to configure these environment variables in your DigitalOcean app settings before deploying._
> feat(auth): add OAuth provider environment variables to app config

- web-app/src/app/app/layout.tsx
Fix app layout.
What was wrong?
App layout doesn't show overflow scroll.
This is related to #163 
How to fix it?
Give static height to both app layout's header and breadcrumb, and set main content as min-h-100svh-header-breadcrumb
> fix(web-app): fix app layout so scroll is visible

- web-app/src/components/breadcrumb-navigation/breadcrumb-navigation.client.tsx
This PR removes the app home route from the breadcrumb navigation to improve UI clarity and reduce redundancy.
Changes:
- Filter out AppRoute.Home from breadcrumb segments
- Maintain existing breadcrumb functionality for all other routes
- Keep minimum segment requirement (2+) for breadcrumb visibility
> fix(navigation): remove app home route from breadcrumb navigation

- web-app/src/config/env.config.ts
- web-app/src/lib/auth/data.ts
Replace usage of nonempty() with min(1) in Zod string validations to follow recommended practices.
- [nonempty()](https://zod.dev/?id=nonempty) is designed specifically for array validation in [Zod](https://zod.dev)
- min(1) is the recommended approach for ensuring non-empty strings
- Updated validation schemas in env.config.ts and auth/data.ts
- No functional changes, only following best practices
This change improves code clarity by using the more appropriate validation method for string fields while maintaining the same validation behavior.
> refactor(validation): replace nonempty() with min(1) in Zod schemas

- web-app/src/app/(landing)/(auth)/forgot-password/components/header.tsx
- Updates the translation namespace from "LandingAuth.Pages.ForgotPassword.Header" to "Landing.Auth.Pages.ForgotPassword.Header" in the forgot password header component
- Verify that forgot password page translations are working correctly
- Ensure no translation keys are missing or showing placeholder text
> fix(auth): update translation namespace for forgot password header

- web-app/prisma/seed.ts
- web-app/src/lib/db/extension/agent.ts
- Changed the price amount format in the seed data from 1500000 to 15_000_000 for better readability.
- Enhanced the getCredits function to handle currency conversion for 'lovelace' and 'usdm' units, ensuring accurate credit calculations.
> fix: update agent pricing format and adjust currency conversion logic

- web-app/src/app/app/jobs/[agentId]/components/create-job-section.tsx
- web-app/src/app/app/jobs/[agentId]/components/right-section.tsx
- web-app/src/app/app/jobs/[agentId]/page.tsx
- web-app/src/lib/db/mocks/input-schema.ts
- web-app/src/lib/db/services/agent.service.ts
🔨 Implements dynamic job input schema fetching from agent API endpoints, replacing hardcoded dummy data.
Changes:
- ✨ Add `getAgentInputSchema` implementation to fetch schema from agent API
- 🔄 Update components to use dynamic schema instead of dummy data
- 🥅 Add error handling with fallback to mock schema
- ♻️ Refactor component props to properly type and pass input schema
This change improves the job creation flow by using real agent input schemas instead of static test data, making the system more dynamic and production-ready.
Missing:
- :fire: Error handling occurs if the `input_schema` cannot be loaded. For now, it is filled with a mock.
> refactor(jobs): migrate from dummy data to dynamic agent input schema

- web-app/src/app/(landing)/(auth)/components/heroes.tsx
- web-app/src/app/(landing)/agents/components/featured-agent.tsx
- web-app/src/app/(landing)/components/how-it-works.tsx
- web-app/src/app/(landing)/components/join-our-community.tsx
- web-app/src/app/(landing)/components/monetize-your-agent.tsx
- web-app/src/components/agents/agent-card.tsx
- web-app/src/components/agents/agent-detail.tsx
Added sizes to next.js Image tag for optimization.
When image uses `fill` property, without `sizes` next.js will assume the image width is 100vw and load unnecessarily big image
https://nextjs.org/docs/pages/api-reference/components/image#sizes
> chore: add sizes props to image for optimization

- job-cron-caller/pnpm-workspace.yaml
- registry-cron-caller/pnpm-workspace.yaml
- web-app/pnpm-workspace.yaml
This PR hoists `prettier` and `eslint` modules to root module directory, so it is possible to import them (even they are hidden modules)
Allow `@prisma/client`'s post install script to run using `onlyBuiltDependencies`
Since pnpm uses strict module resolution (each package is isolated, they don't see each other)
That is why some modules couldn't load `eslint` and `prettier` related packages (they are hidden, not defined in package.json)
https://pnpm.io/settings#publichoistpattern
https://pnpm.io/settings#onlybuiltdependencies
> fix(pnpm): hoist eslint and prettier modules, allow prisma script

- job-cron-caller/package.json
- package.json
- registry-cron-caller/package.json
- web-app/package.json
Updates the `packageManager` field across all `package.json` files to `pnpm@10.8.0` for consistent dependency management tooling.
This also includes minor dependency list formatting and cleanup in `job-cron-caller`, `registry-cron-caller`, and `web-app` packages.
> chore(deps): update pnpm version to 10.8.0

- web-app/prisma/seed.ts
- web-app/src/app/(landing)/agents/components/featured-agent.tsx
- web-app/src/app/(landing)/agents/page.tsx
- web-app/src/app/app/agents/[agentId]/jobs/@right/components/create-job-section.tsx
- web-app/src/app/app/agents/[agentId]/jobs/@right/components/header.tsx
- web-app/src/app/app/agents/[agentId]/jobs/@right/components/job-columns.tsx
- web-app/src/app/app/agents/[agentId]/jobs/@right/components/job-detail-section.tsx
- web-app/src/app/app/agents/[agentId]/jobs/@right/components/job-details.tsx
- web-app/src/app/app/agents/[agentId]/jobs/@right/components/jobs-table.tsx
- web-app/src/app/app/agents/components/filtered-agents.tsx
- web-app/src/app/app/agents/page.tsx
- web-app/src/app/app/components/user-credits.tsx
- web-app/src/components/agents/agent-bookmark-button.tsx
- web-app/src/components/agents/agent-card.tsx
- web-app/src/components/agents/agent-detail.tsx
- web-app/src/components/agents/agents.tsx
- web-app/src/components/breadcrumb-navigation/breadcrumb-navigation.client.tsx
- web-app/src/lib/actions/job.actions.ts
- web-app/src/lib/db/services/agent.service.ts
- web-app/src/lib/db/services/agentList.service.ts
- web-app/src/lib/db/services/credit.service.ts
- web-app/src/lib/db/services/job.service.ts
- web-app/src/lib/db/services/tag.service.ts
- web-app/src/lib/db/services/user.service.ts
- web-app/src/lib/db/types/agent.types.ts
- web-app/src/lib/db/types/agentList.types.ts
- web-app/src/lib/db/types/job.types.ts
- web-app/src/lib/db/utils/credit.utils.ts
This pull request refactors database services and related type definitions for improved organization and consistency.
**Key Changes:**
1.  **Centralized Prisma Types:**
*   Moved Prisma `include` objects and generated types (e.g., `AgentWithRelations`, `JobWithRelations`, `AgentListWithAgent`) from service files (`*.service.ts`) into dedicated files under `src/lib/db/types/`.
*   Updated imports across the codebase to use the new type locations.
2.  **Standardized Credit Handling:**
*   Renamed `getCreditBalance` to `getHumandReadableCreditBalance` for better clarity.
*   Modified credit-related functions in `credit.service.ts` to consistently work with and return human-readable credit amounts (numbers) instead of base units (bigint).
*   Made credit conversion functions …
> refactor(db): centralize types and standardize credit handling

- web-app/messages/en.json
- web-app/src/app/app/agents/[agentId]/jobs/@right/components/job-input/job-input.tsx
- web-app/src/app/app/agents/[agentId]/jobs/@right/components/job-input/job-inputs-form.client.tsx
- web-app/src/app/app/agents/[agentId]/jobs/@right/components/job-input/job-inputs-form.tsx
- web-app/src/lib/job-input/form-schema.ts
- web-app/src/lib/job-input/job-input.ts
* Use index (number) for option values instead of option values
* Remove `transformFormData` function and just add `filterOutNullValues` to filter out `null` value
* Check option data `values` are unique or not
The select (both single and multi) will not work correctly if there is duplicate value in data `values` from schema
Because index is depend on `Array.indexOf` which only takes first index
> fix: update option input values as index number

- web-app/src/lib/actions/stripe.actions.ts
**Description:**
This pull request modifies the `createCheckoutSession` action in `src/lib/actions/stripe.actions.ts`.
Previously, both `customer` (if available) and `customer_email` were potentially being sent to the Stripe Checkout Session creation endpoint. According to Stripe's API documentation, only one of these parameters should be provided. Providing both can lead to errors or unexpected behavior.
This change introduces conditional logic to ensure that:
- If `user.stripeCustomerId` exists, the `customer` parameter is set with this ID.
- If `user.stripeCustomerId` does not exist, the `customer_email` parameter is set with `user.email`.
This ensures compliance with Stripe's API requirements and prevents potential issues during the checkout process.
> fix(stripe): Conditionally set customer or customer_email in checkout session

- web-app/src/app/(landing)/agents/[agentId]/page.tsx
- web-app/src/app/app/agents/[agentId]/page.tsx
This PR removes static generation configuration from agent detail pages in both the landing and app routes, switching to a fully dynamic rendering approach.
- Remove `generateStaticParams` function that was pre-generating paths for agent detail pages
- Remove `revalidate` configuration that was set to 3600 seconds
- Remove `dynamicParams` configuration
- Simplify imports by removing unused `getAgents` function
- Moving to dynamic rendering ensures we always serve fresh agent data without relying on revalidation periods, which is more suitable for frequently updated agent content.
- Newly synced agents on the server causing an `500` error. `DYNAMIC_SERVER_USAGE`
- More consistent and up-to-date agent details
- Reduced build time as we no longer pre-generate agent pages
- Slightly increased …
> refactor(pages): remove static generation from agent detail pages

- web-app/src/lib/db/services/job.service.ts
- Increased `maxWait` from 2000ms to 5000ms
- Increased `timeout` from 5000ms to 10000ms in job start operation
* These changes extend the timeout settings to provide more time for job start operations to complete, reducing the likelihood of premature timeouts during job initialization.
* `start_job` runs in a timeout on `https://dev.sokosumi.com`
Please verify that:
- Job start operations complete successfully with the new timeout values
- No negative impact on system performance with increased timeout durations
> fix(job): adjust timeout settings for job start operation

- web-app/prisma/seed.ts
Adds the 'role' field with a default value of "user" to the seed user creation in the database seeding script.
- Added role field initialization in prisma/seed.ts for the seed user
- Default role is set to "user"
> fix(db): add default role field to seed user

- web-app/src/app/api/stripe/webhook/route.ts
Updates the Stripe webhook handler to return 200 status code for failed transactions instead of 500, while maintaining 500 status for other error scenarios. This change aligns with Stripe's webhook best practices where any non-2xx response will trigger webhook retries.
- Modified error response status codes in `updateFiatTransactionStatus` function to return 200 for failed transactions
- Maintains 500 status code for other error scenarios
- Prevents unnecessary webhook retries from Stripe when a transaction legitimately fails
- Improves webhook reliability and reduces server load from retries
- Follows Stripe's webhook best practices for handling failed transactions
- Verify webhook handles failed transactions correctly
- Confirm successful transactions maintain existing behavior
- Test …
> fix(stripe): adjust webhook response status codes for failed transactions

- web-app/src/app/(landing)/(auth)/forgot-password/components/form.tsx
- web-app/src/app/(landing)/(auth)/reset-password/components/form.tsx
- web-app/src/app/(landing)/(auth)/reset-password/page.tsx
- web-app/src/app/(landing)/components/auth-buttons.tsx
- web-app/src/lib/auth/utils.ts
- web-app/src/middleware/authorization.ts
Change all instances of redirecting to '/signin' to '/login' for consistency across authentication flows.
> fix(auth): update redirect paths from '/signin' to '/login'

- web-app/.cursor/rules/interface.mdc
- web-app/messages/en.json
- web-app/src/app/(landing)/imprint/page.tsx
- web-app/src/app/(landing)/layout.tsx
- web-app/src/app/(landing)/privacy-policy/page.tsx
- web-app/src/app/(landing)/terms-of-service/page.tsx
- web-app/src/components/footer.tsx
This PR introduces new legal pages and updates the footer navigation for the landing section.
- **New Pages:**
- `/imprint`: Imprint page with placeholder content.
- `/privacy-policy`: Privacy Policy page with placeholder content.
- `/terms-of-service`: Terms & Conditions page with placeholder content.
- **Footer Navigation:**
- Links to the new Imprint page.
- Contact link now opens the external Masumi contact page in a new tab.
- Removed Cookie Policy link.
- Uses the new `Footer` translation namespace.
- **Internationalization:**
- Footer navigation translations moved to the new `Footer` namespace in `messages/en.json`.
- Removed old `Landing.Footer` keys.
* Relates to #390 
* Relates to #391 
* Relates to #395
> feat(landing): add imprint, privacy policy, and terms dummy pages; update footer navigation

- web-app/package.json
- web-app/pnpm-lock.yaml
- web-app/prisma/seed.ts
- web-app/src/config/env.config.ts
- web-app/src/lib/db/services/job.service.ts
This PR refactors all usages of Node.js `crypto.randomUUID()` (where relevant to UUID generation) to use the `uuid` package (`v4`), which is now added as a dependency. This change ensures consistent UUID generation across environments and aligns with best practices for cross-platform compatibility.
- Added `uuid@^11.1.0` to dependencies in `package.json` and `pnpm-lock.yaml`.
- Replaced all instances of `crypto.randomUUID()` with `uuidv4()`:
- `prisma/seed.ts`: For `account.id` and `account.accountId`.
- `src/config/env.config.ts`: For default `INSTANCE_ID`.
- `src/lib/db/services/job.service.ts`: For `identifierFromPurchaser`.
- Imported `uuidv4` from the `uuid` package in affected files.
- The `uuid` package is widely adopted, well-maintained, and provides a consistent API for UUID …
> chore: replace Node.js crypto UUID usage with `uuid` package

- web-app/src/app/app/agents/[agentId]/jobs/components/header.tsx
Update job layout's header's `create new job` button.
Use link's href instead of button's onclick (not using "use client")
* Improve SEO
> chore: use link instead of button's onclick

- web-app/messages/en.json
- web-app/src/app/(landing)/components/featured-agents.tsx
This PR introduces internationalization (i18n) for the "Featured Agents" section on the landing page. The section title and button label are now translated using `next-intl`, ensuring a localized experience for users.
- Added `Landing.Page.FeaturedAgents` translations to `messages/en.json`.
- Updated `featured-agents.tsx` to use `getTranslations` from `next-intl/server` for the section title and button.
- Replaced hardcoded strings with translation keys.
- Improves accessibility and user experience for non-English speakers.
- Aligns with our commitment to full internationalization across the app.
- [next-intl documentation](https://next-intl-docs.vercel.app/docs/getting-started/app-router)
---
Relates to #324
> feat(landing): add i18n support for Featured Agents section on landing page 🌍✨

- web-app/src/app/(landing)/components/hero.tsx
- web-app/src/app/(landing)/layout.tsx
- web-app/src/app/globals.css
This PR reorganizes the landing page structure by moving the Kanji logo from the hero component to the landing layout level.
Changes:
- Extracted Kanji logo into a separate component in landing layout
- Removed logo-related code from hero component
- Simplified hero background styling
- Logo is now visible across all landing pages
This change improves component organization by:
- Making the hero component more focused on its core content
- Ensuring consistent logo placement across landing pages
- Following better separation of concerns
> refactor(layout): move kanji logo to landing layout

- .github/dependabot.yml
This PR updates the dependabot configuration with the following changes:
- Change commit message prefix from `build(deps)` to `chore(deps)` across all package ecosystems
- Remove `bytegen-dev` from the reviewers list for all dependency updates
This change better aligns with conventional commit standards where dependency updates are typically categorized under `chore` rather than `build`.
Affected package ecosystems:
- npm (root)
- npm (web-app)
- npm (job-cron-caller)
- npm (registry-cron-caller)
> chore(deps): update dependabot configuration

- web-app/src/app/(landing)/components/how-it-works.tsx
- web-app/src/app/(landing)/components/join-our-community.tsx
- Remove opacity gradient calculation from steps in HowItWorks component
- All steps now have consistent visibility instead of progressive opacity
The opacity gradient was making later steps less visible, which could impact readability and user experience. This change ensures all steps are equally visible and clear to users.
- Removed opacity calculation: `1 / (index + 1 / (steps.length - 1))`
- Simplified map iteration by removing unused index parameter
- Maintained existing spacing and layout structure
> fix(ui): remove opacity gradient from HowItWorks steps

- web-app/messages/en.json
- web-app/src/app/app/components/user-credits.tsx
- Implement low balance detection (≤50 credits)
- Add "Buy Credits" CTA button that appears when balance smaller or equal to `50.0`
- Improve layout with flex container and consistent spacing
- Uses `next-intl` pluralization rules for better i18n support
- Links to billing page for credit purchase
- Maintains consistent UI with Shadcn Button component
- Preserves dark/light mode compatibility
> feat(credits): enhance credit display with low balance CTA

- web-app/messages/en.json
- web-app/package.json
- web-app/pnpm-lock.yaml
- web-app/src/app/app/components/user-avatar/user-avatar.client.tsx
- Integrate Gravatar for user avatars using user's email
- Add support menu item that links to `masumi.network/contact`
- Remove redundant user info label from dropdown menu
- Add `gravatar-url` dependency and related packages
- Add translation for support menu item
- Use `gravatar-url` package to generate avatar URLs with fallback
- Support menu opens in new tab
- Avatar size set to 80px
- Gravatar fallback set to "404"
> feat(user-avatar): integrate gravatar and add support menu item

- web-app/src/app/app/agents/[agentId]/jobs/@right/components/create-job-section.tsx
- web-app/src/app/app/agents/[agentId]/jobs/components/job-columns.tsx
- web-app/src/app/app/agents/[agentId]/jobs/components/jobs-table.tsx
- web-app/src/components/middle-truncate.tsx
Enhances the job creation interface by adding the agent's image to the information accordion panel, providing better visual context for users when creating jobs.
- Add agent image display using Next.js Image component for optimal performance
- Implement responsive layout with flex-wrap for better mobile support
- Configure image with proper dimensions (96x96) and rounded corners
- Maintain text content layout with proper spacing and overflow handling
- Adds a 96x96px agent image with rounded corners
- Maintains existing text layout with proper spacing
> feat(ui): add agent image to job creation information panel

- web-app/src/config/env.config.ts
- web-app/src/lib/services/credit/service.ts
This PR updates the credit pricing logic to ensure that the included fee for credit purchases is never less than the value of 1 credit (in cents). This change guarantees a minimum fee is always applied, regardless of the calculated percentage-based fee.
- Introduced a minimum fee (`minFeeCents`) equal to the value of 1 credit (in cents), using the `convertCreditsToCents` utility.
- After calculating the total fee, the logic now checks if the fee is less than `minFeeCents`. If so, it sets the fee to `minFeeCents`.
- This ensures that very small purchases or low fee percentages still result in a non-zero, meaningful fee.
- Prevents scenarios where the fee could be zero or negligible due to rounding or low purchase amounts.
- Ensures consistent revenue and covers transaction costs for all …
> feat(credits): enforce minimum fee of 1 credit in cents for credit purchases

- web-app/src/app/(auth)/layout.tsx
* Wraps the ThemedLogo component with a Link component in the authentication layout
* Enables navigation to the home page (/) when clicking the logo
* Maintains existing logo styling and priority loading
* This change improves the user experience by:
* Adding a standard navigation pattern where logos link to the home page
* Providing an easy way for users to exit the authentication flow
* Following web conventions for logo behavior
> feat(auth): add home navigation via logo in auth layout

- .github/workflows/deploy-main-webapp.yml
- .github/workflows/deploy-release-web-app.yml
- web-app/.do/app.yaml
- web-app/package.json
- web-app/pnpm-lock.yaml
This PR includes the following changes:
- feat: Add `DIGITALOCEAN_APP_NAME` environment variable to deployment workflows
- feat: Configure dynamic app name in Digital Ocean app configuration using `${DIGITALOCEAN_APP_NAME}`
- refactor: Move service configuration properties to top level in `app.yaml`
- `@prisma/client`: ^6.6.0 → ^6.7.0
- `react-resizable-panels`: ^2.1.8 → ^2.1.9
- `@hey-api/openapi-ts`: ^0.66.6 → ^0.66.7
- `@swc/core`: ^1.11.22 → ^1.11.24
- `prisma`: ^6.6.0 → ^6.7.0
- `tsx`: ^4.19.3 → ^4.19.4
> chore(deps): update dependencies and add DO app name config

- .github/CODEOWNERS
- .github/dependabot.yml
* Remove dependabot's `reviewers` option and add `CODEOWNERS`
https://github.blog/changelog/2025-04-29-dependabot-reviewers-configuration-option-being-replaced-by-code-owners/
> refactor: remove dependabot reviewers option and add CODEOWNERS

- web-app/src/components/agents/agent-card.tsx
This PR addresses an issue where the agent name in the `AgentCard` component was being cut off due to an insufficient line-height. The line-height for the agent name (`h3`) has been increased from `leading-6` to `leading-9`, ensuring the full name is visible and not truncated.  
Additionally, a minor adjustment was made to the `lg` size variant to include `max-w-1/2` for improved layout consistency.
**Changes:**
- Increased line-height for agent name to prevent text cutoff.
- Updated `lg` size variant with `max-w-1/2` for better layout control.
**Reasoning:**  
The previous line-height setting caused longer or larger agent names to be visually truncated, impacting readability and user experience. This fix ensures agent names are fully displayed across all supported sizes.
> fix(agent-card): increase agent name line-height to prevent text cutoff

- .github/workflows/deploy-main-sync-function.yml
- .github/workflows/deploy-release-sync-function.yml
- sync-function/project.yml
- sync-function/src/main.ts
This PR addresses an issue where the API URL was incorrectly constructed in the sync-function deployment and source code. The following changes have been made:
- Replaced all instances of the `SOKOSUMI_API_URL` environment variable with `SOKOSUMI_URL` in workflow files, deployment configuration, and code.
- Updated the API call logic in `sync-function/src/main.ts` to use the correct base URL and endpoint paths, ensuring the URL is constructed properly (e.g., `SOKOSUMI_URL + /api/sync/agents`).
- Updated error messages and environment variable checks to reference `SOKOSUMI_URL`.
- Ensured consistency across GitHub Actions workflows and the `project.yml` configuration.
**Why:**  
The previous implementation incorrectly constructed the API URL, leading to failed requests. This fix ensures …
> fix(sync-function): correct SOKOSUMI_URL usage and API endpoint construction

- web-app/messages/en.json
- web-app/src/app/(auth)/register/components/form.tsx
- web-app/src/config/env.config.ts
- web-app/src/lib/auth/auth.ts
This PR introduces a signup restriction to protect development, staging, and pre-release environments from misuse. Users can now only register with email addresses belonging to explicitly allowed domains, as specified in the `ALLOWED_EMAIL_DOMAINS` environment variable.
- **Environment Variable:**  
Added `ALLOWED_EMAIL_DOMAINS` to the environment config. This variable accepts a comma-separated list of allowed email domains (e.g., `example.com,company.org`). If left empty, no domain restriction is enforced.
- **Auth Middleware:**  
Implemented a `before` hook in the authentication flow to check the domain of the email during signup. If the domain is not allowed, the signup is blocked and a clear error message is shown.
- **Internationalization:**  
Added a new error message for disallowed …
> feat(auth): restrict signup to allowed email domains for non-production environments

- web-app/src/app/(landing)/components/app-connection.tsx
PR Description:
- Changed the `AppConnection` button variant from `secondary` to `primary` in the landing page component.
- Updated the `<Button>` in `web-app/src/app/(landing)/components/app-connection.tsx` to use `variant="primary"` for improved visual prominence and consistency with primary actions.
- Ensures the "Go to App" action stands out as the main call-to-action on the landing page, aligning with UI/UX best practices.
- No breaking changes.
- No impact on functionality; purely a UI/UX improvement.
> fix(button): change "Open App" Button variant from secondary to primary

- web-app/next.config.ts
- web-app/package.json
- web-app/pnpm-lock.yaml
- web-app/src/app/layout.tsx
- web-app/src/config/env.config.ts
This PR introduces Plausible Analytics integration into the Next.js application using the `next-plausible` package. The analytics script is now loaded via a proxy for improved privacy and performance, and the domain is configurable via environment variables.
- **Dependency Added:**  
- `next-plausible@^3.12.4` added to `package.json` and `pnpm-lock.yaml`.
- **Next.js Config:**  
- Wrapped the Next.js config with `withPlausibleProxy` to enable proxying of Plausible scripts.
- **Root Layout:**  
- Added `PlausibleProvider` to the `<head>` of the app, using the domain from environment variables and enabling outbound link tracking.
- **Environment Config:**  
- Added `PLAUSIBLE_DOMAIN` to the environment config with a default value of `sokosumi.com`.
- The Plausible script is loaded and …
> feat(analytics): integrate Plausible analytics into the application

- web-app/next.config.ts
```bash
<w> [webpack.cache.PackFileCacheStrategy] Serializing big strings (318kiB) impacts deserialization performance (consider using Buffer instead and decode when needed)
```
We get this warning because of big middleware bundle size.
* Disable next.js middleware instrument to reduce bundle size
https://github.com/getsentry/sentry-javascript/issues/15100#issuecomment-2732790153
> chore: disable next.js middleware instrument to reduce bundle size

- web-app/.env.example
- web-app/sentry.edge.config.ts
- web-app/sentry.server.config.ts
- web-app/src/config/env.config.ts
- web-app/src/instrumentation-client.ts
* Add sentry dsn as public env variable so we can set that only on production
* Do not receive notification on development (which is annoying)
https://github.com/getsentry/sentry-javascript/discussions/8546#discussioncomment-6556295
> fix: add sentry dsn as public env so we can set that only on production

- web-app/src/components/agents/agents.tsx
This PR updates the alignment of agent cards in the `Agents` component. The flex container's `justify-content` property is changed from `justify-between` to `justify-start`, ensuring that agent cards are aligned to the start of the row rather than being spaced out across the container.
- Updated the `className` in `src/components/agents/agents.tsx`:
- Changed `justify-between` to `justify-start` in the flex container.
- This change improves the visual consistency of agent card alignment, especially when the number of cards does not fill the entire row.
- Aligning cards to the start provides a more predictable and visually appealing layout, particularly for responsive designs and varying card counts.
- Follows UI/UX best practices for card grid layouts.
- Verified that agent cards now …
> fix(ui): align agent cards to start instead of space-between

- web-app/src/components/agents/agents.tsx
This PR reverts the alignment change introduced in #658, restoring the original layout of the agent cards in the Agents component. The flex container now uses justify-between instead of justify-start, ensuring agent cards are spaced evenly across the row as before.
- Reverts: fix(ui): align agent cards to start instead of space-between (#658)
- Affected file: src/components/agents/agents.tsx
- Restores previous flex alignment for improved visual distribution of agent cards
No other changes were made.
> revert(ui): restore agent card alignment to space-between

- sync-function/package.json
- sync-function/pnpm-lock.yaml
- web-app/package.json
- web-app/pnpm-lock.yaml
This pull request updates the pnpm package manager to version 10.11.0 across the project. The update includes changes to the pnpm-lock.yaml and package.json files to ensure compatibility with the latest pnpm features and improvements. This upgrade helps maintain alignment with upstream dependency management best practices and ensures continued support for modern tooling.
Key changes:
- Bumped pnpm version to 10.11.0 in all relevant package.json files.
- Regenerated `pnpm-lock.yaml` to reflect updated dependency resolutions.
- Updated related devDependencies (e.g., eslint, typescript) where required for compatibility.
No application code or runtime dependencies were changed outside of those required for pnpm compatibility. Please review and test your workflows to ensure smooth operation …
> chore(deps): update pnpm to v10.11.0

- web-app/messages/en.json
- web-app/src/app/app/agents/[agentId]/jobs/components/job-status-badge.tsx
This PR updates the job status label from "Payment Pending" to "Payment Processing" throughout the application. The goal is to provide users with a clearer understanding of the current state of their job payments, reducing confusion around whether a payment is awaiting action or actively being processed.
- Updated the English translation key in `messages/en.json`:
- Changed `"paymentPending": "Payment Pending"` to `"paymentProcessing": "Payment Processing"`
- Updated the `JobStatusBadge` component to use the new `paymentProcessing` label.
- "Payment Pending" could be interpreted as requiring user action or waiting for an external event.
- "Payment Processing" more accurately reflects that the system is actively handling the payment, improving user clarity and reducing support inquiries.
- …
> fix(i18n): clarify job status by renaming "Payment Pending" to "Payment Processing"

- web-app/src/app/(landing)/components/endorsements.tsx
This pull request removes Lufthansa and BVG from the endorsements list displayed on the landing page.
- Deleted the Lufthansa and BVG entries from the `endorsements` array in `src/app/(landing)/components/endorsements.tsx`.
- No other logic or UI changes were made.
- The removal was requested to update the list of organizations shown as endorsers.
- Ensures the endorsements section accurately reflects current partnerships.
- Lufthansa and BVG logos will no longer appear in the endorsements section on the landing page.
- No breaking changes or side effects expected.
> refactor(endorsements): remove Lufthansa and BVG from endorsements list

- web-app/src/components/create-job-modal/job-input/job-inputs-form.client.tsx
* Fix duplicated key issues on job input form client's legal links
(Because some of legal links have same href)
> chore: fix duplicate key issue due to same href

- web-app/prisma/migrations/20250520193606_transaction_hash_not_unique/migration.sql
- web-app/prisma/schema.prisma
- web-app/src/lib/db/job/repo.ts
- web-app/src/lib/services/job/service.ts
This PR removes the unique constraint and relation for the on-chain transaction hash from the `Job` model. The previous implementation assumed that each job would have a unique on-chain transaction, but in practice, the transaction hash is not guaranteed to be unique across jobs.
- **Prisma Schema:**  
- Removed the `OnChainTransaction` model and its relation from the `Job` model.
- Replaced the `onChainTransactionId` field with two new fields on `Job`:  
- `onChainTransactionHash: String?`  
- `onChainTransactionStatus: OnChainTransactionStatus?`
- Dropped the unique constraint on the transaction hash.
- **Migration:**  
- Dropped the `OnChainTransaction` table and the `onChainTransactionId` column from `Job`.
- Added the new fields to `Job`.
- **Backend Logic:**  
- Updated all usages …
> refactor(db): remove unique constraint and relation for on-chain transaction hash in Job

- web-app/src/lib/db/job/types.ts
This PR removes the `onChainTransaction` property from the `jobInclude` object in `src/lib/db/job/types.ts`.
- **Removed:** `onChainTransaction: true` from the `jobInclude` object.
- This change likely reflects a shift in how job-related data is queried or a simplification of the job include structure.
- The `onChainTransaction` relation is no longer required in the default job include set, possibly due to changes in data requirements or to optimize query performance.
- This helps keep the data layer lean and focused on currently relevant relations.
- Any queries or services relying on `jobInclude` will no longer automatically include `onChainTransaction` data.
- If this relation is still needed in specific cases, it should be explicitly included where necessary.
> refactor(db/job): remove onChainTransaction from jobInclude

- web-app/src/lib/actions/stripe/action.ts
This PR updates the Stripe checkout session creation logic to allow the use of promotion codes by setting `allow_promotion_codes: true` in the session configuration.
- **File changed:** `src/lib/actions/stripe/action.ts`
- **Change:**  
- Added the `allow_promotion_codes: true` property to the `createCheckoutSession` function's Stripe session payload.
- **Effect:**  
- Users can now enter and apply valid promotion codes during the Stripe checkout process.
Enabling promotion codes improves the flexibility of the checkout experience, allowing users to benefit from discounts and marketing campaigns.
> feat(stripe): enable promotion codes in checkout session creation

- web-app/src/app/app/agents/[agentId]/jobs/@right/components/job-details/job-details.tsx
- web-app/src/app/app/agents/[agentId]/jobs/components/jobs-table.tsx
- web-app/src/app/app/layout.tsx
- web-app/src/app/globals.css
- web-app/src/app/layout.tsx
* Add `max-w-dvw` to `body` tag in app layout so we have width limitation
* Add constant width class name to `JobDetails` component just like `JobTable` because they are both in inline.
* Add job details and job table's width class name to global.css
* Refactor job detail' scroll area (`display: block!`) so it have width limitaion
https://github.com/shadcn-ui/ui/issues/3833
> fix: job detail long content issue

- web-app/messages/en.json
- web-app/src/components/agents/agent-card.tsx
This PR updates the Agent Card component to streamline its call-to-action (CTA) and improve clarity for users:
- **Removes the secondary "Hire Agent" CTA** from the Agent Card, reducing visual clutter and potential confusion.
- **Renames the primary CTA** from "View Agent" to "Show Details" for improved clarity, reflecting that the button only displays agent details and does not initiate a hiring flow.
- Updated the English translation key from `"View Agent"` to `"Show Details"` in `messages/en.json`.
- Replaced the `AgentHireButton` with a single primary button labeled "Show Details" in the Agent Card component.
- Ensured the UI now presents a single, clear action for users to view agent details, aligning with UX best practices.
This change simplifies the Agent Card interface, making it …
> refactor(agent-card): remove secondary CTA and clarify "Show Details" action

- web-app/messages/en.json
- web-app/prisma/migrations/20250522120506_add_marketing_opt_in/migration.sql
- web-app/prisma/schema.prisma
- web-app/src/app/(auth)/register/components/form.tsx
- web-app/src/app/(auth)/register/data.ts
- web-app/src/lib/actions/user/action.ts
- web-app/src/lib/actions/user/index.ts
- web-app/src/lib/db/user/repo.ts
This PR introduces a marketing opt-in checkbox to the user registration flow, allowing new users to choose whether they wish to receive updates and news from Sokosumi.
**Key Changes:**
- Added a new boolean field marketingOptIn to the User model in Prisma, with a default value of false.
- Created a new migration to add the marketingOptIn column to the user table.
- Updated the registration form UI to include a checkbox for marketing opt-in, with internationalized label text.
- Extended the registration form schema and data to support the new checkbox field.
- Implemented backend logic to persist the user's marketing preference during registration via a new updateUserMarketingOptIn server action and supporting repo function.
- Ensured the marketingOptIn value is saved immediately after …
> feat(auth/register): add marketing opt-in checkbox to registration form

- .github/workflows/deploy-main-webapp.yml
- .github/workflows/deploy-release-web-app.yml
This PR updates the GitHub Actions workflows for both main and release deployments of the web application to include a database migration step before deploying. Specifically:
- Adds a step to install pnpm and project dependencies.
- Runs pnpm prisma migrate deploy to apply any pending Prisma migrations to the production database, using the DATABASE_URL secret.
- Ensures the database schema is up-to-date before the deployment step to DigitalOcean.
This change helps prevent schema drift and ensures the application is always deployed with the latest database structure. No application code was modified.
> chore(ci): add database migration step to deployment workflows

- .github/workflows/deploy-main-webapp.yml
- .github/workflows/deploy-release-web-app.yml
This PR fixes misleading step names in GitHub Actions workflows for deployment.
- Updated step name from "Build the app" to "Migrate database" in `deploy-main-webapp.yml`
- Updated step name from "Build the app" to "Migrate database" in `deploy-release-web-app.yml`
The workflow steps were labeled as "Build the app" but were actually running `pnpm prisma migrate deploy`, which performs database migrations. This created confusion about what each step was actually doing.
Renamed the step labels to accurately reflect their purpose: migrating the database schema.
> fix: correct GitHub Actions step names for database migration

- web-app/messages/en.json
- web-app/src/app/app/agents/[agentId]/jobs/@right/components/job-details/download-markdown.tsx
- web-app/src/app/app/agents/[agentId]/jobs/@right/components/job-details/job-details.tsx
- web-app/src/app/app/agents/[agentId]/jobs/@right/components/job-details/outputs.tsx
- web-app/src/app/app/agents/[agentId]/jobs/@right/components/job-details/refund-request.tsx
- web-app/src/components/billing/billing-form.tsx
- web-app/src/lib/api/generated/payment/types.gen.ts
- web-app/src/lib/db/job/repo.ts
- web-app/src/lib/services/job/service.ts
- web-app/src/lib/services/job/third-party.ts
Add refund request functionality to the job details page, allowing users to request refunds for jobs within the allowed timeframe.
- **Refund Request Button**: New button in job details output section to request refunds
- **Smart State Management**: Button shows different states (available, requested, completed)
- **Tooltip Information**: Helpful tooltips explaining refund availability and deadlines
- **Time-based Availability**: Refunds only available until the job's unlock time
- **Error Handling**: Proper error states and loading indicators
- Add new `RequestRefundButton` component with comprehensive state management
- Update job details output layout to include refund functionality alongside download
- Refactor `postPaymentClientRequestRefund` to accept blockchain identifier directly …
> feat: add refund request functionality to job details

- web-app/src/app/(landing)/agents/[agentId]/page.tsx
- web-app/src/app/(landing)/agents/page.tsx
- web-app/src/app/app/agents/[agentId]/page.tsx
- web-app/src/components/agents/agent-card.tsx
- web-app/src/components/agents/agent-detail/section-1.tsx
- web-app/src/components/agents/agent-detail/section-4/playlist-modal.tsx
- web-app/src/components/agents/agent-hire-button.tsx
- web-app/src/components/create-job-modal/create-job-section.tsx
* Update `AgentHireButton` to open create job modal
* Wrap agent detail page (landing, app) with create-job-modal-context-provider, and show modal on CTA "Hire Agent"
* Wrap landing gallery page's Featured Agent with create-job-modal-context-provider to show modal on CTA "Hire Agent"
* Refactor `AgentCard` component not to render `AgentHireButton` when size is not `lg`
* Disable Create Job Modal accordion item while job is submitting
> refactor: cta hire agent opens the new job view

- web-app/src/app/api/sync/jobs/route.ts
Fixes the dispute unlock time condition in the job synchronization query to properly identify jobs that are past their dispute period.
- Changed `externalDisputeUnlockTime` condition from `gt` (greater than) to `lt` (less than) in the job sync query
- This ensures we only process jobs where the 10-minute grace period has actually elapsed
The previous condition (`gt`) was incorrectly selecting jobs where the dispute unlock time was in the future (greater than 10 minutes ago), which would include jobs still within their dispute period.
The corrected condition (`lt`) now properly selects jobs where the dispute unlock time is in the past (less than 10 minutes ago), meaning the dispute period has ended and the job can be processed.
- Jobs will now be correctly identified for processing after …
> fix: correct dispute unlock time condition in job sync query

- web-app/package.json
Fixes incorrect path reference in package.json for the `data-migration:add-cents-to-fiat-transaction` script.
- Updated script path from `20250602120625_add_cents_to_fiat_transaction` to `20250528171822_add_cents_to_fiat_transaction`
- Corrects the migration timestamp to match the actual migration file that exists in the filesystem
- Resolves script execution error when running `pnpm run data-migration:add-cents-to-fiat-transaction`
- Ensures the migration script points to the correct migration directory
- Verified the correct migration directory exists at `prisma/migrations/20250528171822_add_cents_to_fiat_transaction/`
- Script path now correctly references the existing migration
> fix: correct path to add-cents-to-fiat-transaction data migration script

- web-app/package.json
- web-app/pnpm-lock.yaml
- web-app/prisma/migrations/20250528171822_add_cents_to_fiat_transaction/data-migration.ts
- web-app/prisma/migrations/20250602074428_remove_cent_per_amount_on_fiat_transaction/migration.sql
- web-app/prisma/schema.prisma
- web-app/src/lib/db/fiatTransaction/repo.ts
- web-app/src/lib/services/stripe/third-party.ts
This PR cleans up the codebase by removing the deprecated `centsPerAmount` field from the `FiatTransaction` model and all related logic, following the successful migration of all relevant data to the new `cents` field.
- **Prisma Schema:**  
- Removed the `centsPerAmount` field from the `FiatTransaction` model.
- Updated the `cents` field to remove its default value, as it is now always required and set explicitly.
- **Database Migration:**  
- Added a migration to drop the `centsPerAmount` column from the database and update the default for `cents`.
- **Data Migration Script:**  
- Optimized the data migration script to use a single SQL statement for updating `cents` based on the old `centsPerAmount` and `amount` values.
- **Backend Logic:**  
- Removed all references to `centsPerAmount` …
> refactor(db): remove deprecated centsPerAmount field from FiatTransaction

- web-app/messages/en.json
- web-app/src/app/app/agents/[agentId]/jobs/components/job-status-badge.tsx
- web-app/src/lib/db/job/types.ts
- web-app/src/lib/db/job/utils.ts
- web-app/src/lib/services/job/service.ts
Adds a new `OUTPUT_PENDING` job status to better handle cases where results are submitted on-chain but not yet available from the agent, with automatic refund logic when approaching unlock time.
- **Added `OUTPUT_PENDING` status**: Represents jobs where results are submitted on-chain but not available by the agent
- **Updated status enum ordering**: Reorganized `JobStatus` enum for better logical grouping (processing states, payment states, refund/dispute states)
- **Renamed translation key**: `JobStatusBadge` → `StatusBadge` for consistency
- **Updated badge colors**: 
- Processing: blue → sky for better accessibility
- Refund/Dispute resolved: green → purple to distinguish from completed status
- **Added OUTPUT_PENDING badge**: Red styling to indicate attention needed
- **Updated job …
> feat: add OUTPUT_PENDING job status with auto-refund logic

- .github/workflows/claude.yml
Removes the explicit `version: latest` configuration from the pnpm installation step in the Claude Code GitHub Actions workflow.
- Remove `version: latest` from `pnpm/action-setup@v4` step in `.github/workflows/claude.yml`
The `pnpm/action-setup@v4` action automatically detects and uses the pnpm version specified in the `packageManager` field of `package.json` (`pnpm@10.11.1`). Explicitly setting `version: latest` overrides this behavior and could lead to version inconsistencies between local development and CI environments.
By removing this explicit version, we ensure that:
- CI uses the same pnpm version as specified in the project configuration
- Version consistency is maintained across all environments
- The workflow respects the project's package manager version lock
> ci: remove explicit pnpm version from GitHub Actions workflow

- .github/dependabot.yml
- web-app/package.json
- web-app/pnpm-lock.yaml
This PR upgrades Prisma from version 6.8.2 to 6.9.0 and improves the Dependabot configuration for better dependency management.
- ⬆️ Upgrade `@prisma/client` from 6.8.2 to 6.9.0
- ⬆️ Upgrade `prisma` from 6.8.2 to 6.9.0
- 📦 Update all related Prisma package dependencies in lock file
- 🔧 Restructure `.github/dependabot.yml` for better organization
- 🐛 Fix pattern matching for dependency groups:
- `@hey-api/**` → `@hey-api*`
- `radix-ui/**` → `@radix-ui/**`
- 📝 Move common configuration (schedule, limits, commit message) to root level
- ✨ Maintain separate configurations for root and web-app directories
- 🚀 Benefits from Prisma 6.9.0 improvements and bug fixes
- 🔄 More reliable dependency grouping in Dependabot PRs
- 🛠️ Cleaner and more maintainable Dependabot configuration
> chore(deps): upgrade prisma to 6.9.0 and improve dependabot config

- web-app/src/components/breadcrumb-navigation/breadcrumb-navigation.client.tsx
* Use next/link instead of <a> link in breadcrumb for better user experience.
* There is no entire reloading when user clicks breadcrumb link.
> refactor(breadcrumb): use next/link

- web-app/src/app/globals.css
- web-app/src/components/agents/agent-card.tsx
* Make utility class name `agent-card-image-shadow` for glow effect
* Add glow effect for `xs`, `sm`, `md` variants of `AgentCard`
* For now glow effect use `muted-foreground` color
> refactor(ui): add glow effect on agent card

- web-app/messages/en.json
This PR updates all user-facing instances of "Sokosumi" to "Sōkosumi" (with a macron over the 'o') in the English i18n messages file (`web-app/messages/en.json`).
- Replaces "Sokosumi" with "Sōkosumi" in modal descriptions, metadata titles, marketing opt-in labels, email subjects, and other relevant strings.
- Ensures consistent branding and correct spelling across the application.
- No functional or logic changes; this is a content update for improved localization and brand accuracy.
The change aligns the application's user-facing text with the correct and intended spelling of the product name, supporting branding consistency and localization best practices.
- Affected file: `web-app/messages/en.json`
- No other files or logic are modified.
---
**Please review for any missed instances or …
> fix(i18n): update branding to "Sōkosumi" in English messages

- web-app/src/app/(auth)/login/components/form.tsx
* Revalidate router cache after user logs in to show updated session information in user avatar component
* Because we have UserAvatar component in `/app` layout.tsx, which is stored in router cache and data is not re-fetched on client-side navigation.
> fix: revalidate router cache after user log in

- web-app/.vscode/extensions.json
This PR removes the duplicate recommendation for the `bradlc.vscode-tailwindcss` extension from the `.vscode/extensions.json` file in the `web-app` directory.
- The `bradlc.vscode-tailwindcss` extension was listed twice in the recommendations. This PR removes the duplicate, ensuring only unique extension recommendations are present.
- Keeps the VSCode extension recommendations clean and avoids confusion for contributors.
---
This PR follows the [Conventional Commits 1.0.0](https://www.conventionalcommits.org/en/v1.0.0/) specification.
> chore: remove duplicate VSCode extension recommendation for Tailwind CSS

- web-app/prisma/migrations/20250616093348_add_input_schema_to_job/migration.sql
- web-app/prisma/migrations/20250616100850_remove_input_schema_default/migration.sql
- web-app/prisma/schema.prisma
- web-app/src/app/app/agents/[agentId]/jobs/@right/components/job-details/inputs.tsx
- web-app/src/app/app/agents/[agentId]/jobs/@right/components/job-details/job-details.tsx
- web-app/src/components/create-job-modal/job-input/job-inputs-form.client.tsx
- web-app/src/lib/db/job/repo.ts
- web-app/src/lib/services/job/schemas.ts
- web-app/src/lib/services/job/service.ts
This PR enhances the Job Detail page by introducing support for displaying job input fields with descriptive labels, leveraging the new `inputSchema` property on the `Job` model. This improves clarity and user experience by mapping input field IDs to human-readable names.
- **Database:**
- Added a required `inputSchema` JSONB column to the `Job` table (with migration).
- **Backend:**
- Passes and persists the input schema when creating jobs.
- Updates service and validation logic to handle the new schema.
- **Frontend:**
- The Job Details UI now displays input fields using descriptive names from the schema, not just raw keys.
- Improved type safety and error handling for input parsing.
- All UI changes follow Shadcn UI, Radix, and Tailwind best practices, with full i18n support via …
> feat(job-detail): display input fields with descriptive labels and schema support

- web-app/src/components/agents/agent-card.tsx
- web-app/src/components/agents/agent-detail/section-1.tsx
- web-app/src/lib/db/agent/types.ts
- web-app/src/lib/db/agent/utils.ts
- Show `authorOrganization` with higher priority than `authorName` throughout the interface.
- On the detail page, show both: `authorOrganization (authorName)` if both are present.
- Refactored agent author utility functions for clarity and future extensibility.
- Show the `authorOrganization` if given with a higher priority as the `authorName`.
- On the detail page show both: `authorOrganization (authorName)`.
> feat(agent): display author organization in place of author name

- web-app/public/js/plain.js
This pull request updates the URL for reporting an agentic service in the Plain JS plugin from a Google Form to a Tally.so form.
> fix(web-app): update plain.js report URL

- web-app/messages/en.json
- web-app/src/components/billing/billing-form.tsx
- web-app/src/lib/actions/billing/action.ts
- web-app/src/lib/actions/billing/index.ts
- web-app/src/lib/errors/coupon-errors.ts
- web-app/src/lib/services/stripe/service.ts
- web-app/src/lib/services/stripe/third-party.ts
This pull request introduces functionality for users to redeem Stripe coupons for a fixed amount of free credits. The billing form has been updated to support either purchasing credits directly or applying a coupon code, but not both simultaneously.
*   **`web-app/src/components/billing/billing-form.tsx`**:
*   The form now exclusively accepts either a credit purchase amount or a coupon code.
*   Inputting a value in one field (credits or coupon) automatically clears the other, ensuring a clear user flow.
*   Form validation (`zod`) has been updated to enforce that one of the two fields must be filled.
*   Submitting a coupon triggers the new `getFreeCreditsWithCoupon` action.
*   **`web-app/src/lib/actions/billing/action.ts`**:
*   Introduced `getFreeCreditsWithCoupon`, a new server …
> feat(billing): implement coupon redemption for fixed-amount credits

- web-app/src/lib/db/agent/utils.ts
- web-app/src/lib/services/agent/third-party.ts
- web-app/src/lib/services/job/third-party.ts
Fixes the `new Url("/example",baseUrl)`if the baseURL of the agent already contained path segments like `/api/v1/`
> fix: url path adding when agent urls contained path segments

- web-app/src/app/(landing)/components/endorsements.tsx
This PR adds the BVG (Berliner Verkehrsbetriebe) logo to the logos section on the sokosumi landing page.
**Details:**
- Integrates the BVG logo alongside existing partner logos.
- Ensures correct placement and visual consistency with other logos.
- Uses responsive design principles for optimal display on all devices.
- Follows Shadcn UI, Radix, and Tailwind CSS conventions for styling.
- Maintains accessibility and supports both dark and light modes.
This update enhances the landing page by representing BVG as a key partner, improving brand visibility and trust.
> feat(landing): add BVG logo to logos section on landing page

- .github/workflows/deploy-main-sync-function.yml
- .github/workflows/deploy-main-webapp.yml
- .github/workflows/deploy-release-sync-function.yml
- .github/workflows/deploy-release-web-app.yml
- Update concurrency group names in deployment workflows to be unique per workflow.
- Prevents overlap and ensures correct concurrency control for:
- main-sync-function
- main-webapp
- release-sync-function
- release-webapp
Previously, all main deployments used 'staging-deployment' and all release deployments used 'production-deployment' as their concurrency group. This could cause jobs to block each other unintentionally. Now, each workflow has a unique group name, improving deployment isolation and reliability.
No application code or infrastructure logic is changed—only workflow concurrency group names.
> ci: use unique concurrency groups for each deployment workflow

- web-app/prisma/seed.ts
- web-app/src/lib/services/stripe/third-party.ts
This PR removes usage of `server-only` function in seed script and use `process.env` directly.
Because `server-only` can only be used from Next.js Server Component not regular node.js environment.
> fix: prisma migration seed script

- web-app/messages/en.json
- web-app/src/app/api/sync/jobs/route.ts
- web-app/src/app/app/agents/[agentId]/jobs/components/job-status-badge.tsx
- web-app/src/app/app/components/sidebar/components/agent-job-status-indicator.tsx
- web-app/src/lib/db/helpers/job.ts
- web-app/src/lib/db/repositories/job.ts
- web-app/src/lib/services/job/service.ts
This PR refines the logic for handling jobs stuck in "payment pending" or "payment failed" states, and improves the UI badge display for these statuses.
- **Job Status Logic:**
- Introduces a 5-minute grace period for jobs without a purchase before marking them as `PAYMENT_FAILED`.
- Returns `PAYMENT_PENDING` for jobs without a purchase within the grace period.
- Ensures jobs already refunded are marked as `REFUND_RESOLVED`.
- Refactors `computeJobStatus` for clarity and correctness.
- **UI Updates:**
- Adds a new "Payment Processing" badge for the `PAYMENT_PENDING` state in the job status badge component.
- Updates i18n messages to include the new `paymentPending` label.
- **Repository/Service:**
- Ensures idempotency in the refund logic (no double refunds).
- Cleans up job sync logic to …
> fix(job): improve payment pending/failed logic and UI for jobs without purchase

- web-app/src/app/app/agents/[agentId]/jobs/layout.tsx
- web-app/src/app/app/agents/[agentId]/jobs/loading.tsx
- web-app/src/app/app/agents/loading.tsx
- web-app/src/app/app/agents/page.tsx
- web-app/src/app/app/components/header.tsx
- web-app/src/app/app/layout.tsx
This PR refines the layout and spacing of key UI sections for improved consistency and alignment across the app:
- **Header**: Moves padding from internal elements to the header container, ensuring consistent spacing and removing redundant `px-4` from child components.
- **Main Content**: Adds `p-4` padding to the main content area for better content alignment and visual balance.
- **Footer**: Standardizes footer padding to `p-4` for uniformity across breakpoints.
- **Agents Gallery**: Removes extra horizontal padding from the agents gallery page to align with the new layout structure.
These changes address inconsistencies in padding and spacing between the header, main content, and footer, resulting in a cleaner and more cohesive user interface. This also simplifies responsive design and …
> fix(ui): adjust padding for header, main, and agents gallery for consistent layout

- pnpm-lock.yaml
This pull request updates the better-call package to version 1.0.12.
**Summary of changes:**
- Upgraded better-call dependency to v1.0.12.
**Reason for change:**
- Ensures the project uses the latest features, improvements, and bug fixes provided in better-call v1.0.12.
- https://github.com/masumi-network/sokosumi/security/dependabot/11
**Checklist:**
Please review and let me know if further adjustments are needed.
> chore: update better-call to v1.0.12

- web-app/src/app/(landing)/components/agents-showcase/agents-showcase.client.tsx
This PR updates the Agents Showcase component to display the short author name instead of the agent description. Specifically, it replaces the usage of `getAgentDescription` with `getShortAgentAuthorName` for the `description` prop in both the main and mapped `AgentShowcaseCard` components.
- Updated imports to use `getShortAgentAuthorName` from `@/lib/db`.
- Replaced all instances of `getAgentDescription(agent)` with `getShortAgentAuthorName(agent)` in `agents-showcase.client.tsx`.
- The UI now shows the short author name beneath each agent's name, providing a more concise and relevant context for users.
This change improves the clarity and relevance of the information shown in the Agents Showcase, making it easier for users to quickly identify the author of each agent.
- No changes were …
> refactor(agents-showcase): replace agent description with short author name

- web-app/src/app/(auth)/components/form/auth-form.tsx
- web-app/src/app/(auth)/components/form/base-form.tsx
- web-app/src/app/(auth)/login/components/form.tsx
- web-app/src/app/(auth)/register/components/form.tsx
- web-app/src/app/layout.tsx
- web-app/src/components/create-job-modal/job-input/job-inputs-form.client.tsx
This PR enhances analytics tracking by integrating Plausible's tagged event system into key forms and updates the PlausibleProvider configuration for improved event capture.
**Key changes:**
- Added a `className` prop to `AuthForm` and `BaseForm` components to allow passing Plausible event tags.
- Updated the sign-in, sign-up, and job input forms to include Plausible event name classes (`plausible-event-name=SignIn`, `plausible-event-name=Signup`, `plausible-event-name=Hire`).
- Modified the PlausibleProvider in `layout.tsx` to enable `pageviewProps` and `taggedEvents` for more granular analytics.
- Ensured all changes follow accessibility and code quality standards, and maintain compatibility with both light and dark modes.
**Motivation:**  
These changes enable more precise tracking of …
> feat(analytics): add Plausible tagged event tracking to auth and job forms

- web-app/src/components/create-job-modal/job-input/job-inputs-form.client.tsx
This PR refactors the JobInputsFormClient component to improve navigation handling by replacing the useRouter hook from next/navigation with a custom useAsyncRouter hook. All router.push calls are now awaited to ensure proper navigation flow, especially in async contexts such as toast action handlers.
**Key changes:**
- Replaced useRouter with useAsyncRouter for navigation.
- Updated all router.push calls to be awaited, including those in toast action handlers.
- Ensured navigation actions are handled asynchronously for better reliability and user experience.
This change improves navigation consistency and prevents potential issues with unawaited navigation in async event handlers. No user-facing changes are expected.
> refactor(job-inputs-form): use useAsyncRouter for navigation and await router.push

- web-app/src/lib/job-input/form-schema.ts
This PR updates the Zod schema generation logic for job input forms to ensure that fields marked as optional are actually treated as optional in the form validation. Previously, optional fields were incorrectly set as `nullable()`, which did not align with expected form behavior. This change replaces `.nullable()` with `.optional()` for all relevant job input types (string, textarea, number, option).
- Updated the schema builders in `form-schema.ts` for string, textarea, number, and option input types.
- Now, when a job input is marked as optional, the generated Zod schema uses `.optional()` instead of `.nullable()`.
- This ensures that optional fields are not required by the form and can be omitted entirely, matching user expectations and improving UX.
- Users can now submit forms …
> fix(form): make optional job inputs truly optional in form schema

- web-app/src/app/api/sync/agents/route.ts
- web-app/src/app/api/sync/jobs/route.ts
- web-app/src/app/api/sync/route.ts
- web-app/src/lib/auth/utils.ts
- web-app/vercel.json
Vercel's cron jobs always trigger endpoints using the GET method, but our `/api/sync/agents` and `/api/sync/jobs` endpoints previously only supported POST for authenticated sync operations. This caused scheduled syncs to fail, as GET requests were not handled for these endpoints.
- Added GET handlers to `/api/sync/agents` and `/api/sync/jobs` that authenticate using the cron secret and trigger the sync logic.
- Refactored authentication:  
- GET requests now require the cron secret (for Vercel cron compatibility).
- POST requests require the admin API key (for manual/admin-triggered syncs).
- Removed the now-unused `authenticateApiRequest` helper.
- Updated Vercel cron configuration to point directly to `/api/sync/agents` and `/api/sync/jobs` with appropriate schedules.
- Vercel cron jobs …
> fix(api/sync): support GET for Vercel cron triggers and split agent/job sync endpoints

- web-app/src/app/(landing)/layout.tsx
- web-app/src/app/(landing)/page.tsx
This PR fixes landing page's layout to match with updated header. (we now add banner to header)
* Fix landing page's main content's padding to `pt-30` because landing header's height is `h-30`.
* Fix landing page's hero section's margin to `-mt-30`.
* Fix landing page's main content's min width to `min-w-[calc(100svh-120px)]`.
> fix: landing layout

- web-app/vercel.json
This PR updates the Vercel serverless function schedule for the `/api/sync/jobs` endpoint.  
- **Change:** The cron schedule is modified from running every minute (`* * * * *`) to every 2 minutes (`*/2 * * * *`).
- **Reason:** This adjustment reduces the frequency of job sync executions, which can help optimize resource usage and prevent unnecessary load.
No other changes are included in this PR.  
Please review and merge if the new schedule aligns with operational requirements.
> chore(vercel): update /api/sync/jobs cron schedule to every 2 minutes

- web-app/src/app/api/sync/agents/route.ts
- web-app/src/app/api/sync/jobs/route.ts
- web-app/src/config/env.secrets.ts
- Updated the sync endpoints (`/api/sync/agents` and `/api/sync/jobs`) to return HTTP status **409 Conflict** instead of **429 Too Many Requests** when a sync lock is already in place. This provides a more semantically correct response for resource locking scenarios.
- Reduced the default `LOCK_TIMEOUT` in `env.secrets.ts` from **10 minutes** to **2 minutes** to allow faster recovery from stale locks and improve system responsiveness.
- **409 Conflict** is the appropriate status code for resource contention, indicating that the request could not be completed due to a conflict with the current state of the resource (i.e., a sync is already in progress).
- Shortening the lock timeout minimizes the risk of long lockouts due to unexpected failures or crashes, improving the user and developer …
> fix(api): return 409 Conflict for sync lock and reduce lock timeout to 2 minutes

- web-app/src/lib/db/repositories/lock.ts
- web-app/vercel.json
This PR updates the `unlockLock` function in `web-app/src/lib/db/repositories/lock.ts` to return a `boolean` instead of a `Lock | null`. The function now returns `true` if the lock was successfully unlocked and `false` if the lock was not locked, providing a clearer and more idiomatic API for distributed lock management.
- Refactored `unlockLock` to return a `boolean` indicating success or failure.
- Updated the function documentation to reflect the new return type and behavior.
- The function now uses `updateMany` for atomicity and checks the affected row count to determine the result.
- Removed the unnecessary `findFirst` query after unlocking, improving performance and reducing database load.
- Returning a boolean is more intuitive for consumers of the API, as it directly answers …
> fix(db): update unlockLock to return boolean for atomic lock release

- web-app/sentry.edge.config.ts
- web-app/sentry.server.config.ts
- web-app/src/instrumentation-client.ts
This PR disables `sendDefaultPii` option from Sentry configuration, because this causes next.js application warning.
https://github.com/getsentry/sentry-javascript/issues/16542
> fix: disable sendDefaultPii until sentry fixes their issue

- web-app/src/app/(landing)/components/header/auth-buttons.tsx
- Changed the default authentication button in the landing page header from "Sign In" to "Sign Up" to better guide new users towards registration
- Maintains existing logic to show "Sign In" when users are on the registration page
- Updated `auth-buttons.tsx` to return `SignUpButton` by default instead of `SignInButton`
- This encourages new visitors to register rather than assuming they already have an account
> fix(header): change default auth button from SignIn to SignUp on landing page

- web-app/src/app/api/sync/agents/route.ts
- web-app/src/app/api/sync/jobs/route.ts
- Fix proper error handling for `unlockLock` calls in sync endpoints
- Add await for `unlockLock` calls and log failures when unlock operations fail
- Remove unnecessary await for `syncAllJobs` call that was causing timing issues
- Add return type annotation for `syncAllJobs` function
- Add logging for job sync count
- `src/app/api/sync/agents/route.ts`: Properly await `unlockLock` and handle failures
- `src/app/api/sync/jobs/route.ts`: Fix unlock handling and improve function typing
> fix(api): handle unlockLock failure in agentSync and jobSync functions

- web-app/src/lib/auth/utils.ts
This PR get session from database every time not from cache.
Because we face `UnAuthenticated` Error sometimes.
And we think the reason is that the cookie’s signature or expiration isn’t consistent.
Such as when the session data and its signature use slightly different expiry values, the session check can fail, causing `getSession` to return null.
https://github.com/better-auth/better-auth/pull/3283
> refactor: disable cookie cache when call getSession

- pnpm-lock.yaml
- web-app/src/app/(app)/organizations/[organizationSlug]/page.tsx
- web-app/src/components/members-table/members-table.tsx
- web-app/src/lib/auth/auth.ts
- web-app/src/lib/db/repositories/invitation.repository.ts
- web-app/src/lib/services/organization.service.ts
This PR ensures we only show one pending invitation per user on members table.
When there are many pending invitations for one user, we only show the latest one (sort by `expiresAt`)
* Remove unnecessary organization service function `getOrganizationPendingInvitations` and invitation repo function `getPendingInvitationsByOrganizationId`
* Use `better-auth` api to get all invitation and sort them by `expiresAt` and pick one per user's email.
> fix: show only one latest invitation per user

- web-app/src/app/(app)/agents/[agentId]/jobs/components/header.tsx
- web-app/src/components/agents/agent-card.tsx
- web-app/src/components/agents/agent-modal.tsx
- Fix agent detail modal on job detail page to fit the screen width (use `display: block;` instead of `display: table;`)
- Fix agent author logo position to bottom right.
> fix: agent modal on job detail page

- pnpm-lock.yaml
- pnpm-workspace.yaml
- web-app/messages/en.json
- web-app/next.openapi.json
- web-app/package.json
- web-app/public/openapi.json
- web-app/src/app/(app)/components/header-api-docs.tsx
- web-app/src/app/api-docs/layout.tsx
- web-app/src/app/api-docs/page.tsx
- web-app/src/app/api/v1/agents/[agentId]/input-schema/route.ts
- web-app/src/app/api/v1/agents/[agentId]/jobs/route.ts
- web-app/src/app/api/v1/agents/route.ts
- web-app/src/app/api/v1/jobs/[jobId]/route.ts
- web-app/src/app/api/v1/jobs/route.ts
- web-app/src/app/api/v1/users/me/route.ts
- web-app/src/lib/api/types/agent.ts
- web-app/src/lib/api/types/job.ts
- web-app/src/lib/api/types/user.ts
- web-app/src/middleware.ts
Introduces a public OpenAPI specification and an in-app API docs page to improve API discoverability for external consumers and keep server responses aligned with documented schemas. Also adds generated TypeScript types for API entities.
- OpenAPI spec: add `public/openapi.json` and `next.openapi.json` for publishing and local usage
- Docs UI: add `app/api-docs` route and `HeaderApiDocs` component
- Generated API types: add `src/lib/api/types/{agent,job,user}.ts`
- Route alignments: minor updates in `v1` endpoints (agents, jobs, users) for parity with the spec
- Chore: update lockfile to include new assets and scripts
- Unit tests pass (job input schema)
- ESLint passes with no warnings
- Pre-push hooks succeeded
- No breaking API changes expected
- No DB migrations
- DEV-495
I'm using a …
> feat(api): publish OpenAPI spec and docs

- web-app/src/lib/job-input/form-schema.ts
- web-app/src/lib/job-input/form.ts
- This PR allows `null` value for optional field (`null` is default value for most of Input types)
- By the zod v4 migration, we are using deprecated functions (`z.string().email()`, `z.string().url()`, ...), which will be fixed by follow-up PR
> fix(job-input): update form schema to allow nullable optional fields

- web-app/src/middleware.ts
Enable public cross-origin access for `api/v1` endpoints. Adds preflight `OPTIONS` handling and attaches CORS headers to all `api/v1` responses.
- **CORS in middleware**: Add CORS logic for paths starting with `/api/v1` in `web-app/src/middleware.ts`.
- **Preflight support**: Return `204` for `OPTIONS` requests with CORS headers.
- **Headers added**:
- `Access-Control-Allow-Origin: *`
- `Access-Control-Allow-Methods: GET, POST, PUT, PATCH, DELETE, OPTIONS`
- `Access-Control-Allow-Headers: Content-Type, Authorization, X-Requested-With, x-api-key`
- `Access-Control-Max-Age: 86400`
- **Matcher updated**: Include `'/api/v1/:path*'` in `middleware.config.matcher`.
- **Exclusion removed**: Remove `'/api/v1'` from middleware `EXCLUDED_PATHS`.
Allow third-party clients to call public API …
> fix(cors): apply matcher for /api/v1 and remove exclusion

- web-app/package.json
- web-app/prisma/migrations/20250907123348_add_job_share_allow_search_indexing/migration.sql
- web-app/prisma/migrations/20250907124911_add_token_allow_search_indexing_to_job_share/data-migration.ts
- web-app/prisma/migrations/20250907124911_add_token_allow_search_indexing_to_job_share/migration.sql
- web-app/prisma/schema.prisma
- web-app/src/app/share/jobs/[jobId]/page.tsx
- web-app/src/lib/services/job.service.ts
This PR enhances the job sharing functionality by adding token-based security features. It introduces a unique token system for job shares and adds the ability to control search engine indexing.
- **Added unique token field** to `JobShare` model for secure access control
- **Implemented token-based sharing** where each job share gets a unique token
- **Updated service method** from `getSharedJob` to `getPubliclySharedJob` for better semantic clarity
- **Added `allowSearchIndexing` field** to control whether shared jobs can be indexed by search engines
- **Default value set to `true`** to maintain current behavior while allowing future customization
- **New migration** (`20250907124911_add_token_allow_search_indexing_to_job_share`) that:
- Adds `token` column with unique constraint
- Adds …
> refactor: add token to job share model

- web-app/messages/en.json
- web-app/src/components/copyable-value.tsx
- web-app/src/components/jobs/job-details/job-meta-details.tsx
Refactored the `HashValue` component into a more generic `CopyableValue` component that can be reused for any copyable text values, not just hashes. This improves code maintainability and enables the job ID to have the same copy functionality as hash values.
- **Component Refactoring**: Renamed `HashValue` to `CopyableValue` for better semantic clarity
- Renamed `hash-value.tsx` → `copyable-value.tsx`
- Updated interface: `HashValueProps` → `CopyableValueProps`
- Updated component function name
- **Job ID Enhancement**: Job ID now displays with copy-to-clipboard functionality using the refactored component
- Changed from plain `MiddleTruncate` to `CopyableValue` component
- Uses `agentJobId` instead of internal `id`
- **Icon Sizing Fix**: Updated icon sizing from `h-4 w-4` to `size-4` …
> refactor(components): generalize HashValue to CopyableValue component
